In [6]:
# import library 

import pandas as pd
import numpy as np

In [19]:
# load dataset

cc_fraud = pd.read_csv('../data/credit_card_fraud_dataset.csv')

In [20]:

# menampilkan 5 baris pertama data 

cc_fraud.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0

In [21]:
# ubah TransactionDate menjadi datetime
cc_fraud['TransactionDate'] = pd.to_datetime(cc_fraud['TransactionDate'], errors='coerce')

cc_fraud.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0

In [22]:
# cek info apakah sudah terubah dtype nya menjadi datetime.
cc_fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   TransactionID    100000 non-null  int64
 1   TransactionDate  100000 non-null  datetime64[ns]
 2   Amount           100000 non-null  float64
 3   MerchantID       100000 non-null  int64
 4   TransactionType  100000 non-null  object
 5   Location         100000 non-null  object
 6   IsFraud          100000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 5.3+ MB

In [23]:
# membuat sebuah kolom HourofDay dan kolom DayofWeek.

cc_fraud['HourofDay'] = cc_fraud['TransactionDate'].dt.hour
cc_fraud['DayofWeek'] = cc_fraud['TransactionDate'].dt.day_of_week
cc_fraud.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4

In [24]:
# membuat sebuah kolom boolean Is_Night_Transaction yang bernilai True jika transaksi terjadi antara jam 00:00 hingga 05:00 pagi (waktu rawan fraud).

cc_fraud['Is_Night_Transaction'] = cc_fraud['HourofDay'] < 6
cc_fraud.head(10)

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2,False
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1,False
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0,False
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5,False
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4,False
5,6,2024-08-30 01:52:35.462867,3086.22,302,purchase,New York,0,1,4,True
6,7,2024-01-02 11:31:35.462875,1466.90,902,refund,Philadelphia,0,11,1,False
7,8,2024-05-12 12:25:35.462885,917.21,266,purchase,New York,0,12,6,False
8,9,2023-11-16 02:20:35.462894,1625.73,32,refund,Chicago,0,2,3,True
9,10,2023-10-24 06:51:35.462901,662.07,193,purchase,Dallas,0,6,1,False

In [25]:
# membuat sebuah  kolom Risk_Level dengan kategori Critical, Medium, Low
cc_fraud['Risk_Level'] = np.where((cc_fraud['Amount'] > 4000) & (cc_fraud['TransactionType'] == "refund"), 'Critical', np.where(cc_fraud['Amount'].between(2000,4000),'Medium','Low'))

In [26]:
cc_fraud.head(10) # menampilkan 10 baris awal data

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2,False,Critical
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1,False,Medium
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0,False,Low
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5,False,Medium
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4,False,Low
5,6,2024-08-30 01:52:35.462867,3086.22,302,purchase,New York,0,1,4,True,Medium
6,7,2024-01-02 11:31:35.462875,1466.90,902,refund,Philadelphia,0,11,1,False,Low
7,8,2024-05-12 12:25:35.462885,917.21,266,purchase,New York,0,12,6,False,Low
8,9,2023-11-16 02:20:35.462894,1625.73,32,refund,Chicago,0,2,3,True,Low
9,10,2023-10-24 06:51:35.462901,662.07,193,purchase,Dallas,0,6,1,False,Low

In [28]:
# Buat kolom Flag_Suspicious.
# Berikan nilai 1 jika transaksi terjadi di 'New York' atau 'Houston' dengan Amount di atas rata-rata (mean) seluruh transaksi, jika tidak 0.

mean_amount = cc_fraud['Amount'].mean()

# Cara (Vectorized)
cc_fraud['Flag_Suspicious'] = np.where(
    (cc_fraud['Location'].isin(["New York", "Houston"])) & (cc_fraud['Amount'] > mean_amount),
    1, 
    0
)

# menampilkan dataset
cc_fraud

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level,Flag_Suspicious
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2,False,Critical,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1,False,Medium,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0,False,Low,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5,False,Medium,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4,False,Low,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,2024-06-07 00:57:36.027591,1057.29,289,refund,San Antonio,0,0,4,True,Low,0
99996,99997,2023-10-22 23:12:36.027594,297.25,745,refund,San Antonio,0,23,6,False,Low,0
99997,99998,2024-05-31 19:27:36.027597,3448.56,690,purchase,San Antonio,0,19,4,False,Medium,0
99998,99999,2024-10-18 09:43:36.027601,3750.79,644,purchase,Philadelphia,0,9,4,False,Medium,0
99999,100000,2024-03-05 19:41:36.027606,1596.79,675,refund,Houston,0,19,1,False,Low,0

In [29]:
cc_fraud.query('Flag_Suspicious == 1') # menampilkan data dengan suspecious 1

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level,Flag_Suspicious
5,6,2024-08-30 01:52:35.462867,3086.22,302,purchase,New York,0,1,4,True,Medium,1
12,13,2024-08-31 02:38:35.462922,2855.69,219,refund,New York,0,2,5,True,Medium,1
16,17,2024-01-04 22:23:35.462948,2721.95,912,refund,New York,0,22,3,False,Medium,1
26,27,2024-09-22 11:17:35.463015,4186.42,725,purchase,New York,0,11,6,False,Low,1
38,39,2024-08-09 09:02:35.463100,3204.04,663,purchase,Houston,0,9,4,False,Medium,1
...,...,...,...,...,...,...,...,...,...,...,...,...
99965,99966,2023-11-14 05:36:36.027463,3468.88,437,refund,Houston,0,5,1,True,Medium,1
99976,99977,2024-06-23 11:12:36.027527,2961.80,866,refund,Houston,0,11,6,False,Medium,1
99977,99978,2023-11-23 04:08:36.027530,2690.97,541,refund,New York,0,4,3,True,Medium,1
99987,99988,2024-07-20 13:42:36.027564,4778.32,767,refund,New York,0,13,5,False,Critical,1
99990,99991,2024-01-12 17:50:36.027574,2883.93,231,refund,New York,0,17,4,False,Medium,1

In [31]:
# membuat sebuah kolom locatio code
cc_fraud['Location_Code'] = cc_fraud['Location'].str[0:3].str.upper()


# menampilkan dataset
cc_fraud

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level,Flag_Suspicious,Location_Code
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2,False,Critical,0,SAN
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1,False,Medium,0,DAL
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0,False,Low,0,NEW
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5,False,Medium,0,PHI
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4,False,Low,0,PHO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,2024-06-07 00:57:36.027591,1057.29,289,refund,San Antonio,0,0,4,True,Low,0,SAN
99996,99997,2023-10-22 23:12:36.027594,297.25,745,refund,San Antonio,0,23,6,False,Low,0,SAN
99997,99998,2024-05-31 19:27:36.027597,3448.56,690,purchase,San Antonio,0,19,4,False,Medium,0,SAN
99998,99999,2024-10-18 09:43:36.027601,3750.79,644,purchase,Philadelphia,0,9,4,False,Medium,0,PHI
99999,100000,2024-03-05 19:41:36.027606,1596.79,675,refund,Houston,0,19,1,False,Low,0,HOU

In [32]:
# menghapus kolom MerchantID

cc_fraud.drop(columns=['MerchantID'], inplace=True)

cc_fraud

,TransactionID,TransactionDate,Amount,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level,Flag_Suspicious,Location_Code
0,1,2024-04-03 14:15:35.462794,4189.27,refund,San Antonio,0,14,2,False,Critical,0,SAN
1,2,2024-03-19 13:20:35.462824,2659.71,refund,Dallas,0,13,1,False,Medium,0,DAL
2,3,2024-01-08 10:08:35.462834,784.00,purchase,New York,0,10,0,False,Low,0,NEW
3,4,2024-04-13 23:50:35.462850,3514.40,purchase,Philadelphia,0,23,5,False,Medium,0,PHI
4,5,2024-07-12 18:51:35.462858,369.07,purchase,Phoenix,0,18,4,False,Low,0,PHO
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,2024-06-07 00:57:36.027591,1057.29,refund,San Antonio,0,0,4,True,Low,0,SAN
99996,99997,2023-10-22 23:12:36.027594,297.25,refund,San Antonio,0,23,6,False,Low,0,SAN
99997,99998,2024-05-31 19:27:36.027597,3448.56,purchase,San Antonio,0,19,4,False,Medium,0,SAN
99998,99999,2024-10-18 09:43:36.027601,3750.79,purchase,Philadelphia,0,9,4,False,Medium,0,PHI
99999,100000,2024-03-05 19:41:36.027606,1596.79,refund,Houston,0,19,1,False,Low,0,HOU

In [34]:
# rename kolom IsFraud menjadi Target_Label
cc_fraud.rename(columns={'IsFraud':'Target_Label'}, inplace=True)

cc_fraud

,TransactionID,TransactionDate,Amount,TransactionType,Location,Target_Label,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level,Flag_Suspicious,Location_Code
0,1,2024-04-03 14:15:35.462794,4189.27,refund,San Antonio,0,14,2,False,Critical,0,SAN
1,2,2024-03-19 13:20:35.462824,2659.71,refund,Dallas,0,13,1,False,Medium,0,DAL
2,3,2024-01-08 10:08:35.462834,784.00,purchase,New York,0,10,0,False,Low,0,NEW
3,4,2024-04-13 23:50:35.462850,3514.40,purchase,Philadelphia,0,23,5,False,Medium,0,PHI
4,5,2024-07-12 18:51:35.462858,369.07,purchase,Phoenix,0,18,4,False,Low,0,PHO
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,2024-06-07 00:57:36.027591,1057.29,refund,San Antonio,0,0,4,True,Low,0,SAN
99996,99997,2023-10-22 23:12:36.027594,297.25,refund,San Antonio,0,23,6,False,Low,0,SAN
99997,99998,2024-05-31 19:27:36.027597,3448.56,purchase,San Antonio,0,19,4,False,Medium,0,SAN
99998,99999,2024-10-18 09:43:36.027601,3750.79,purchase,Philadelphia,0,9,4,False,Medium,0,PHI
99999,100000,2024-03-05 19:41:36.027606,1596.79,refund,Houston,0,19,1,False,Low,0,HOU

In [36]:
# save update dataframe
cc_fraud.to_csv('../data/fraud_analysis_final_2026.csv')