# Akses Data dengan Library Pandas

In [1]:
import pandas as pd

In [5]:
# load dataset dengan variabel yang dibuat
coffe = pd.read_csv('data/coffee.csv')

In [6]:
coffe.head()        # untuk melihat 5 baris pertama dari data coffee

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [7]:
coffe       # untuk melihat semua dataframe

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [8]:
# Membuat sebuah data random atau sebuah sample dari data coffe
coffe.sample(10, random_state=1)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [9]:
# Akses Data dengan loc dan iloc
coffe

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [12]:
# memberi tahu value dari dataframe berdasarkan baris yang ingin di ketahui dengan sebuah label atau nama index atau column bisa dengan values nya atau label nya


coffe.loc[1]

Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object

In [13]:
coffe.loc[[1,2,6]]

        Day Coffee Type  Units Sold
1    Monday       Latte          15
2   Tuesday    Espresso          30
6  Thursday    Espresso          40

In [14]:
# dengan sebuah loc kita bisa tau ingin mengambil value apa dari sebuah dataframe.
coffe.loc[:,["Day","Units Sold","Coffee Type"]]

          Day  Units Sold Coffee Type
0      Monday          25    Espresso
1      Monday          15       Latte
2     Tuesday          30    Espresso
3     Tuesday          20       Latte
4   Wednesday          35    Espresso
5   Wednesday          25       Latte
6    Thursday          40    Espresso
7    Thursday          30       Latte
8      Friday          45    Espresso
9      Friday          35       Latte
10   Saturday          45    Espresso
11   Saturday          35       Latte
12     Sunday          45    Espresso
13     Sunday          35       Latte

In [16]:
# sama dengan loc bedanya iloc harus menggunakan angka.
coffe.iloc[:,[0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [17]:
coffe

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [18]:
# mengatur sebuah dataframe values dengan loc/iloc

coffe.loc[1:3, "Units Sold"] = 10

In [19]:
coffe

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

### mengambil sebuah kolom, memfilter (sort) nilai, ascending - descending

In [20]:
coffee_new = pd.read_csv('data/coffee.csv')

In [21]:
coffee_new

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [22]:
# sort values dari dataframe coffee
coffee_new.sort_values(by='Units Sold')

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [23]:
# sort values dari dataframe coffee dari terbesar ke terkecil
coffee_new.sort_values(['Units Sold','Coffee Type'], ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [24]:
# untuk mengambil sebuah kolom
coffee_new['Coffee Type']

0     Espresso
1        Latte
2     Espresso
3        Latte
4     Espresso
5        Latte
6     Espresso
7        Latte
8     Espresso
9        Latte
10    Espresso
11       Latte
12    Espresso
13       Latte
Name: Coffee Type, dtype: object

# Praktek

In [25]:
praktik_coffee = pd.read_csv('data/coffee.csv')

In [26]:
praktik_coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [33]:
# 4 baris pertama Dataframe 
praktik_coffee.head(4)

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [34]:
# 2 baris terakhir DataFrame
praktik_coffee.tail(2)

       Day Coffee Type  Units Sold
12  Sunday    Espresso          45
13  Sunday       Latte          35

In [35]:
# 3 baris acak dari data DataFrame 
praktik_coffee.sample(3)

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
12     Sunday    Espresso          45
6    Thursday    Espresso          40

In [36]:
# menggunakan iloc mengambil data baris ke - 5 sampai ke - 8
praktik_coffee.iloc[5:9]

         Day Coffee Type  Units Sold
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45

In [37]:
# menggunakan iloc untuk mengambil jumlah 'units sold' pada 5 baris pertama
praktik_coffee.iloc[0:6,2]

0    25
1    15
2    30
3    20
4    35
5    25
Name: Units Sold, dtype: int64

In [38]:
# Gunakan loc untuk menampilkan baris indeks 10 sampai 12, tapi hanya kolom 'Day' dan 'Units Sold'.
praktik_coffee.loc[10:12,["Day","Units Sold"]]

         Day  Units Sold
10  Saturday          45
11  Saturday          35
12    Sunday          45

In [39]:
# jumlah unit yang terjual di baris indeks 0? Ambil nilainya saja pakai iloc.
praktik_coffee.iloc[0,2]

np.int64(25)