# Adding / Removing Columns

In [1]:
import pandas as pd
import numpy as np

In [3]:
# load dataset coffee
coffe = pd.read_csv('data/coffee.csv')

In [ ]:
# menampilkan 5 baris pertama dataset
coffe.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [5]:
# adding columns dengan nama price

coffe['price'] = 3.00

In [7]:
coffe.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25    3.0
1     Monday       Latte          15    3.0
2    Tuesday    Espresso          30    3.0
3    Tuesday       Latte          20    3.0
4  Wednesday    Espresso          35    3.0

In [8]:
# membuat sebuah case uni dimana harga tiap tipe coffe berbeda

coffe['new_price'] = np.where(coffe['Coffee Type'] == 'Latte', 6.00, 5.30)

In [9]:
coffe

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25    3.0        5.3
1      Monday       Latte          15    3.0        6.0
2     Tuesday    Espresso          30    3.0        5.3
3     Tuesday       Latte          20    3.0        6.0
4   Wednesday    Espresso          35    3.0        5.3
5   Wednesday       Latte          25    3.0        6.0
6    Thursday    Espresso          40    3.0        5.3
7    Thursday       Latte          30    3.0        6.0
8      Friday    Espresso          45    3.0        5.3
9      Friday       Latte          35    3.0        6.0
10   Saturday    Espresso          45    3.0        5.3
11   Saturday       Latte          35    3.0        6.0
12     Sunday    Espresso          45    3.0        5.3
13     Sunday       Latte          35    3.0        6.0

In [10]:
# menghapus sebuah columns seperti contoh diatas menggantikan price dengan new_price
coffe.drop(columns=['price'])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25        5.3
1      Monday       Latte          15        6.0
2     Tuesday    Espresso          30        5.3
3     Tuesday       Latte          20        6.0
4   Wednesday    Espresso          35        5.3
5   Wednesday       Latte          25        6.0
6    Thursday    Espresso          40        5.3
7    Thursday       Latte          30        6.0
8      Friday    Espresso          45        5.3
9      Friday       Latte          35        6.0
10   Saturday    Espresso          45        5.3
11   Saturday       Latte          35        6.0
12     Sunday    Espresso          45        5.3
13     Sunday       Latte          35        6.0

In [12]:
# jika di run ulang di coffe tidak akan terhapus karena fungsi ini menghilangkan apa yang diperintahkan tanpa menyimpan dataset baru yang sudah di edit
coffe

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25    3.0        5.3
1      Monday       Latte          15    3.0        6.0
2     Tuesday    Espresso          30    3.0        5.3
3     Tuesday       Latte          20    3.0        6.0
4   Wednesday    Espresso          35    3.0        5.3
5   Wednesday       Latte          25    3.0        6.0
6    Thursday    Espresso          40    3.0        5.3
7    Thursday       Latte          30    3.0        6.0
8      Friday    Espresso          45    3.0        5.3
9      Friday       Latte          35    3.0        6.0
10   Saturday    Espresso          45    3.0        5.3
11   Saturday       Latte          35    3.0        6.0
12     Sunday    Espresso          45    3.0        5.3
13     Sunday       Latte          35    3.0        6.0

In [15]:
# untuk bener bener mengubah nya hingga ke database maka yang perlu dilakukan yaitu menciptakan sebuah kondis dengan Inplace = True
coffe.drop(columns=['price'], inplace=True)

In [17]:
# sebuah dataset baru yang disimpan setelah kita memodifikasi nya dengan menggunakan sebuah inplace = True
coffe

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25        5.3
1      Monday       Latte          15        6.0
2     Tuesday    Espresso          30        5.3
3     Tuesday       Latte          20        6.0
4   Wednesday    Espresso          35        5.3
5   Wednesday       Latte          25        6.0
6    Thursday    Espresso          40        5.3
7    Thursday       Latte          30        6.0
8      Friday    Espresso          45        5.3
9      Friday       Latte          35        6.0
10   Saturday    Espresso          45        5.3
11   Saturday       Latte          35        6.0
12     Sunday    Espresso          45        5.3
13     Sunday       Latte          35        6.0

In [18]:
'''
ada 2 cara sebenernya untuk mengubah sebuah dataset yang sudah di modifikasi dengan cara :
coffe = coffe.drop(columns=['price'])

atau 

coffe.drop(columns=['price'], inplace=True)
'''

"\nada 2 cara sebenernya untuk mengubah sebuah dataset yang sudah di modifikasi dengan cara :\ncoffe = coffe.drop(columns=['price'])\n\natau \n\ncoffe.drop(columns=['price'], inplace=True)\n"

In [20]:
# kita bisa memodifikasi sebuah dataset dengan keinginan kolom apa saja yang ingin ditampilkan dalam dataset kita
coffe = coffe[['Day','Coffee Type','Units Sold','new_price']]

In [21]:
coffe

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25        5.3
1      Monday       Latte          15        6.0
2     Tuesday    Espresso          30        5.3
3     Tuesday       Latte          20        6.0
4   Wednesday    Espresso          35        5.3
5   Wednesday       Latte          25        6.0
6    Thursday    Espresso          40        5.3
7    Thursday       Latte          30        6.0
8      Friday    Espresso          45        5.3
9      Friday       Latte          35        6.0
10   Saturday    Espresso          45        5.3
11   Saturday       Latte          35        6.0
12     Sunday    Espresso          45        5.3
13     Sunday       Latte          35        6.0

In [ ]:
# kita ingin menambahkan sebuah kolon pendapatan
coffe['Revenue'] = coffe['Units Sold'] * coffe['new_price']

# kita bisa melakukan sebuah aritmatika untuk mengasiggning value dalam variabel kolom baru kita

In [23]:
coffe

          Day Coffee Type  Units Sold  new_price  Revenue
0      Monday    Espresso          25        5.3    132.5
1      Monday       Latte          15        6.0     90.0
2     Tuesday    Espresso          30        5.3    159.0
3     Tuesday       Latte          20        6.0    120.0
4   Wednesday    Espresso          35        5.3    185.5
5   Wednesday       Latte          25        6.0    150.0
6    Thursday    Espresso          40        5.3    212.0
7    Thursday       Latte          30        6.0    180.0
8      Friday    Espresso          45        5.3    238.5
9      Friday       Latte          35        6.0    210.0
10   Saturday    Espresso          45        5.3    238.5
11   Saturday       Latte          35        6.0    210.0
12     Sunday    Espresso          45        5.3    238.5
13     Sunday       Latte          35        6.0    210.0

In [24]:
# semisal kita ingin mengganti nama kolom new_price dengan price
coffe.rename(columns = {'new_price':'price'})

          Day Coffee Type  Units Sold  price  Revenue
0      Monday    Espresso          25    5.3    132.5
1      Monday       Latte          15    6.0     90.0
2     Tuesday    Espresso          30    5.3    159.0
3     Tuesday       Latte          20    6.0    120.0
4   Wednesday    Espresso          35    5.3    185.5
5   Wednesday       Latte          25    6.0    150.0
6    Thursday    Espresso          40    5.3    212.0
7    Thursday       Latte          30    6.0    180.0
8      Friday    Espresso          45    5.3    238.5
9      Friday       Latte          35    6.0    210.0
10   Saturday    Espresso          45    5.3    238.5
11   Saturday       Latte          35    6.0    210.0
12     Sunday    Espresso          45    5.3    238.5
13     Sunday       Latte          35    6.0    210.0

In [25]:
# lagii, jika kita ingin mengubah ini masuk ke dalam dataset kita harus menggunakan salah satu cara dari 2 yang tadi diatas
coffe = coffe.rename(columns = {'new_price':'price'})

In [26]:
coffe

          Day Coffee Type  Units Sold  price  Revenue
0      Monday    Espresso          25    5.3    132.5
1      Monday       Latte          15    6.0     90.0
2     Tuesday    Espresso          30    5.3    159.0
3     Tuesday       Latte          20    6.0    120.0
4   Wednesday    Espresso          35    5.3    185.5
5   Wednesday       Latte          25    6.0    150.0
6    Thursday    Espresso          40    5.3    212.0
7    Thursday       Latte          30    6.0    180.0
8      Friday    Espresso          45    5.3    238.5
9      Friday       Latte          35    6.0    210.0
10   Saturday    Espresso          45    5.3    238.5
11   Saturday       Latte          35    6.0    210.0
12     Sunday    Espresso          45    5.3    238.5
13     Sunday       Latte          35    6.0    210.0

## Praktek Adding/Removing Columns

In [29]:
# ini merupakan sebuah praktik pribadi tanpa melihat apapun berdasarkan apa yang telah di pelajari di segmentasi ini

# load dataset coffe namun karena sudah ada dan kita tidak mau mengubah nya maka kita akan meload nya dengan variabel baru dengan menggunakan Fungsi .copy()

new_coffee = coffe.copy()

In [30]:
new_coffee.head()

         Day Coffee Type  Units Sold  price  Revenue
0     Monday    Espresso          25    5.3    132.5
1     Monday       Latte          15    6.0     90.0
2    Tuesday    Espresso          30    5.3    159.0
3    Tuesday       Latte          20    6.0    120.0
4  Wednesday    Espresso          35    5.3    185.5

In [31]:
# Membuat sebuah kolom baru bernama total_spent.
new_coffee['total_spent'] = new_coffee['Units Sold'] * new_coffee['price']

In [32]:
new_coffee

          Day Coffee Type  Units Sold  price  Revenue  total_spent
0      Monday    Espresso          25    5.3    132.5        132.5
1      Monday       Latte          15    6.0     90.0         90.0
2     Tuesday    Espresso          30    5.3    159.0        159.0
3     Tuesday       Latte          20    6.0    120.0        120.0
4   Wednesday    Espresso          35    5.3    185.5        185.5
5   Wednesday       Latte          25    6.0    150.0        150.0
6    Thursday    Espresso          40    5.3    212.0        212.0
7    Thursday       Latte          30    6.0    180.0        180.0
8      Friday    Espresso          45    5.3    238.5        238.5
9      Friday       Latte          35    6.0    210.0        210.0
10   Saturday    Espresso          45    5.3    238.5        238.5
11   Saturday       Latte          35    6.0    210.0        210.0
12     Sunday    Espresso          45    5.3    238.5        238.5
13     Sunday       Latte          35    6.0    210.0        210.0

In [34]:
# menghapus kolom revenue dari new_coffe
new_coffee = new_coffee.drop(columns=['Revenue'])

In [36]:
new_coffee

          Day Coffee Type  Units Sold  price  total_spent
0      Monday    Espresso          25    5.3        132.5
1      Monday       Latte          15    6.0         90.0
2     Tuesday    Espresso          30    5.3        159.0
3     Tuesday       Latte          20    6.0        120.0
4   Wednesday    Espresso          35    5.3        185.5
5   Wednesday       Latte          25    6.0        150.0
6    Thursday    Espresso          40    5.3        212.0
7    Thursday       Latte          30    6.0        180.0
8      Friday    Espresso          45    5.3        238.5
9      Friday       Latte          35    6.0        210.0
10   Saturday    Espresso          45    5.3        238.5
11   Saturday       Latte          35    6.0        210.0
12     Sunday    Espresso          45    5.3        238.5
13     Sunday       Latte          35    6.0        210.0

In [40]:
# buat kolom promo_price dimana jika coffee type nya itu espresso maka diskon hingga 2.99 jika bukan maka 5.99

new_coffee['promo_price'] = np.where(new_coffee['Coffee Type'] == 'Espresso',2.99,5.99)

In [41]:
new_coffee

          Day Coffee Type  Units Sold  price  total_spent  promo_price
0      Monday    Espresso          25    5.3        132.5         2.99
1      Monday       Latte          15    6.0         90.0         5.99
2     Tuesday    Espresso          30    5.3        159.0         2.99
3     Tuesday       Latte          20    6.0        120.0         5.99
4   Wednesday    Espresso          35    5.3        185.5         2.99
5   Wednesday       Latte          25    6.0        150.0         5.99
6    Thursday    Espresso          40    5.3        212.0         2.99
7    Thursday       Latte          30    6.0        180.0         5.99
8      Friday    Espresso          45    5.3        238.5         2.99
9      Friday       Latte          35    6.0        210.0         5.99
10   Saturday    Espresso          45    5.3        238.5         2.99
11   Saturday       Latte          35    6.0        210.0         5.99
12     Sunday    Espresso          45    5.3        238.5         2.99
13     Sunday       Latte          35    6.0        210.0         5.99

In [46]:
# mengubah nama kolom Units Sold menjadi jumlah_terjual dan kolom price menjadi harga_satuan 
new_coffee.rename(columns={'Units Sold': 'jumlah_terjual'}, inplace=True)
new_coffee.rename(columns={'price':'harga_satuan'}, inplace=True)

In [47]:
new_coffee

,Day,Coffee Type,jumlah_terjual,harga_satuan,total_spent,promo_price
0,Monday,Espresso,25,5.3,132.5,2.99
1,Monday,Latte,15,6.0,90.0,5.99
2,Tuesday,Espresso,30,5.3,159.0,2.99
3,Tuesday,Latte,20,6.0,120.0,5.99
4,Wednesday,Espresso,35,5.3,185.5,2.99
5,Wednesday,Latte,25,6.0,150.0,5.99
6,Thursday,Espresso,40,5.3,212.0,2.99
7,Thursday,Latte,30,6.0,180.0,5.99
8,Friday,Espresso,45,5.3,238.5,2.99
9,Friday,Latte,35,6.0,210.0,5.99
10,Saturday,Espresso,45,5.3,238.5,2.99
11,Saturday,Latte,35,6.0,210.0,5.99
12,Sunday,Espresso,45,5.3,238.5,2.99
13,Sunday,Latte,35,6.0,210.0,5.99

In [55]:
# menghapus kolom total_spent
new_coffee.drop(columns=['harga_satuan'],inplace=True)

In [56]:
new_coffee

,Day,Coffee Type,jumlah_terjual,promo_price,status_penjualan,tax_amount
0,Monday,Espresso,25,2.99,Under Performance,0.53
1,Monday,Latte,15,5.99,Under Performance,0.60
2,Tuesday,Espresso,30,2.99,Target Achieved,0.53
3,Tuesday,Latte,20,5.99,Under Performance,0.60
4,Wednesday,Espresso,35,2.99,Target Achieved,0.53
5,Wednesday,Latte,25,5.99,Under Performance,0.60
6,Thursday,Espresso,40,2.99,Target Achieved,0.53
7,Thursday,Latte,30,5.99,Target Achieved,0.60
8,Friday,Espresso,45,2.99,Target Achieved,0.53
9,Friday,Latte,35,5.99,Target Achieved,0.60
10,Saturday,Espresso,45,2.99,Target Achieved,0.53
11,Saturday,Latte,35,5.99,Target Achieved,0.60
12,Sunday,Espresso,45,2.99,Target Achieved,0.53
13,Sunday,Latte,35,5.99,Target Achieved,0.60

In [57]:
# membuat sebuah kolom status_penjualan 

new_coffee['status_penjualan'] = np.where(new_coffee['jumlah_terjual'] > 25, "Target Achieved", "Under Performance")

In [58]:
new_coffee

,Day,Coffee Type,jumlah_terjual,promo_price,status_penjualan,tax_amount
0,Monday,Espresso,25,2.99,Under Performance,0.53
1,Monday,Latte,15,5.99,Under Performance,0.60
2,Tuesday,Espresso,30,2.99,Target Achieved,0.53
3,Tuesday,Latte,20,5.99,Under Performance,0.60
4,Wednesday,Espresso,35,2.99,Target Achieved,0.53
5,Wednesday,Latte,25,5.99,Under Performance,0.60
6,Thursday,Espresso,40,2.99,Target Achieved,0.53
7,Thursday,Latte,30,5.99,Target Achieved,0.60
8,Friday,Espresso,45,2.99,Target Achieved,0.53
9,Friday,Latte,35,5.99,Target Achieved,0.60
10,Saturday,Espresso,45,2.99,Target Achieved,0.53
11,Saturday,Latte,35,5.99,Target Achieved,0.60
12,Sunday,Espresso,45,2.99,Target Achieved,0.53
13,Sunday,Latte,35,5.99,Target Achieved,0.60

In [59]:
# membuat sebuah kolom tax_amount dengan isi 10% dari pajak
new_coffee['tax_amount'] = new_coffee['promo_price'] * 10/100

In [60]:
new_coffee

,Day,Coffee Type,jumlah_terjual,promo_price,status_penjualan,tax_amount
0,Monday,Espresso,25,2.99,Under Performance,0.299
1,Monday,Latte,15,5.99,Under Performance,0.599
2,Tuesday,Espresso,30,2.99,Target Achieved,0.299
3,Tuesday,Latte,20,5.99,Under Performance,0.599
4,Wednesday,Espresso,35,2.99,Target Achieved,0.299
5,Wednesday,Latte,25,5.99,Under Performance,0.599
6,Thursday,Espresso,40,2.99,Target Achieved,0.299
7,Thursday,Latte,30,5.99,Target Achieved,0.599
8,Friday,Espresso,45,2.99,Target Achieved,0.299
9,Friday,Latte,35,5.99,Target Achieved,0.599
10,Saturday,Espresso,45,2.99,Target Achieved,0.299
11,Saturday,Latte,35,5.99,Target Achieved,0.599
12,Sunday,Espresso,45,2.99,Target Achieved,0.299
13,Sunday,Latte,35,5.99,Target Achieved,0.599

In [64]:
# mengubah kolom Coffee type menjadi jenis_kopi

new_coffee.rename(columns={'Coffee Type':'jenis_kopi'}, inplace=True)

In [65]:
new_coffee

,Day,jenis_kopi,jumlah_terjual,promo_price,status_penjualan,tax_amount
0,Monday,Espresso,25,2.99,Under Performance,0.299
1,Monday,Latte,15,5.99,Under Performance,0.599
2,Tuesday,Espresso,30,2.99,Target Achieved,0.299
3,Tuesday,Latte,20,5.99,Under Performance,0.599
4,Wednesday,Espresso,35,2.99,Target Achieved,0.299
5,Wednesday,Latte,25,5.99,Under Performance,0.599
6,Thursday,Espresso,40,2.99,Target Achieved,0.299
7,Thursday,Latte,30,5.99,Target Achieved,0.599
8,Friday,Espresso,45,2.99,Target Achieved,0.299
9,Friday,Latte,35,5.99,Target Achieved,0.599
10,Saturday,Espresso,45,2.99,Target Achieved,0.299
11,Saturday,Latte,35,5.99,Target Achieved,0.599
12,Sunday,Espresso,45,2.99,Target Achieved,0.299
13,Sunday,Latte,35,5.99,Target Achieved,0.599

In [66]:
# membuat sebuah kolom baru bernama final_price dengan isi promo_price + tax_amount
new_coffee['final_price'] = new_coffee['promo_price'] + new_coffee['tax_amount']

In [67]:
new_coffee

,Day,jenis_kopi,jumlah_terjual,promo_price,status_penjualan,tax_amount,final_price
0,Monday,Espresso,25,2.99,Under Performance,0.299,3.289
1,Monday,Latte,15,5.99,Under Performance,0.599,6.589
2,Tuesday,Espresso,30,2.99,Target Achieved,0.299,3.289
3,Tuesday,Latte,20,5.99,Under Performance,0.599,6.589
4,Wednesday,Espresso,35,2.99,Target Achieved,0.299,3.289
5,Wednesday,Latte,25,5.99,Under Performance,0.599,6.589
6,Thursday,Espresso,40,2.99,Target Achieved,0.299,3.289
7,Thursday,Latte,30,5.99,Target Achieved,0.599,6.589
8,Friday,Espresso,45,2.99,Target Achieved,0.299,3.289
9,Friday,Latte,35,5.99,Target Achieved,0.599,6.589
10,Saturday,Espresso,45,2.99,Target Achieved,0.299,3.289
11,Saturday,Latte,35,5.99,Target Achieved,0.599,6.589
12,Sunday,Espresso,45,2.99,Target Achieved,0.299,3.289
13,Sunday,Latte,35,5.99,Target Achieved,0.599,6.589

In [1]:
# testing github