# Adding / Removing Columns

In [3]:
import pandas as pd
import numpy as np

In [2]:
# load dataset coffee
coffe = pd.read_csv('data/coffee.csv')

In [3]:
# menampilkan 5 baris pertama dataset
coffe.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [4]:
# adding columns dengan nama price

coffe['price'] = 3.00

In [5]:
coffe.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25    3.0
1     Monday       Latte          15    3.0
2    Tuesday    Espresso          30    3.0
3    Tuesday       Latte          20    3.0
4  Wednesday    Espresso          35    3.0

In [6]:
# membuat sebuah case uni dimana harga tiap tipe coffe berbeda

coffe['new_price'] = np.where(coffe['Coffee Type'] == 'Latte', 6.00, 5.30)

In [7]:
coffe

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25    3.0        5.3
1      Monday       Latte          15    3.0        6.0
2     Tuesday    Espresso          30    3.0        5.3
3     Tuesday       Latte          20    3.0        6.0
4   Wednesday    Espresso          35    3.0        5.3
5   Wednesday       Latte          25    3.0        6.0
6    Thursday    Espresso          40    3.0        5.3
7    Thursday       Latte          30    3.0        6.0
8      Friday    Espresso          45    3.0        5.3
9      Friday       Latte          35    3.0        6.0
10   Saturday    Espresso          45    3.0        5.3
11   Saturday       Latte          35    3.0        6.0
12     Sunday    Espresso          45    3.0        5.3
13     Sunday       Latte          35    3.0        6.0

In [8]:
# menghapus sebuah columns seperti contoh diatas menggantikan price dengan new_price
coffe.drop(columns=['price'])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25        5.3
1      Monday       Latte          15        6.0
2     Tuesday    Espresso          30        5.3
3     Tuesday       Latte          20        6.0
4   Wednesday    Espresso          35        5.3
5   Wednesday       Latte          25        6.0
6    Thursday    Espresso          40        5.3
7    Thursday       Latte          30        6.0
8      Friday    Espresso          45        5.3
9      Friday       Latte          35        6.0
10   Saturday    Espresso          45        5.3
11   Saturday       Latte          35        6.0
12     Sunday    Espresso          45        5.3
13     Sunday       Latte          35        6.0

In [9]:
# jika di run ulang di coffe tidak akan terhapus karena fungsi ini menghilangkan apa yang diperintahkan tanpa menyimpan dataset baru yang sudah di edit
coffe

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25    3.0        5.3
1      Monday       Latte          15    3.0        6.0
2     Tuesday    Espresso          30    3.0        5.3
3     Tuesday       Latte          20    3.0        6.0
4   Wednesday    Espresso          35    3.0        5.3
5   Wednesday       Latte          25    3.0        6.0
6    Thursday    Espresso          40    3.0        5.3
7    Thursday       Latte          30    3.0        6.0
8      Friday    Espresso          45    3.0        5.3
9      Friday       Latte          35    3.0        6.0
10   Saturday    Espresso          45    3.0        5.3
11   Saturday       Latte          35    3.0        6.0
12     Sunday    Espresso          45    3.0        5.3
13     Sunday       Latte          35    3.0        6.0

In [10]:
# untuk bener bener mengubah nya hingga ke database maka yang perlu dilakukan yaitu menciptakan sebuah kondis dengan Inplace = True
coffe.drop(columns=['price'], inplace=True)

In [11]:
# sebuah dataset baru yang disimpan setelah kita memodifikasi nya dengan menggunakan sebuah inplace = True
coffe

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25        5.3
1      Monday       Latte          15        6.0
2     Tuesday    Espresso          30        5.3
3     Tuesday       Latte          20        6.0
4   Wednesday    Espresso          35        5.3
5   Wednesday       Latte          25        6.0
6    Thursday    Espresso          40        5.3
7    Thursday       Latte          30        6.0
8      Friday    Espresso          45        5.3
9      Friday       Latte          35        6.0
10   Saturday    Espresso          45        5.3
11   Saturday       Latte          35        6.0
12     Sunday    Espresso          45        5.3
13     Sunday       Latte          35        6.0

In [12]:
'''
ada 2 cara sebenernya untuk mengubah sebuah dataset yang sudah di modifikasi dengan cara :
coffe = coffe.drop(columns=['price'])

atau 

coffe.drop(columns=['price'], inplace=True)
'''

"\nada 2 cara sebenernya untuk mengubah sebuah dataset yang sudah di modifikasi dengan cara :\ncoffe = coffe.drop(columns=['price'])\n\natau \n\ncoffe.drop(columns=['price'], inplace=True)\n"

In [13]:
# kita bisa memodifikasi sebuah dataset dengan keinginan kolom apa saja yang ingin ditampilkan dalam dataset kita
coffe = coffe[['Day','Coffee Type','Units Sold','new_price']]

In [14]:
coffe

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25        5.3
1      Monday       Latte          15        6.0
2     Tuesday    Espresso          30        5.3
3     Tuesday       Latte          20        6.0
4   Wednesday    Espresso          35        5.3
5   Wednesday       Latte          25        6.0
6    Thursday    Espresso          40        5.3
7    Thursday       Latte          30        6.0
8      Friday    Espresso          45        5.3
9      Friday       Latte          35        6.0
10   Saturday    Espresso          45        5.3
11   Saturday       Latte          35        6.0
12     Sunday    Espresso          45        5.3
13     Sunday       Latte          35        6.0

In [15]:
# kita ingin menambahkan sebuah kolon pendapatan
coffe['Revenue'] = coffe['Units Sold'] * coffe['new_price']

# kita bisa melakukan sebuah aritmatika untuk mengasiggning value dalam variabel kolom baru kita

In [16]:
coffe

          Day Coffee Type  Units Sold  new_price  Revenue
0      Monday    Espresso          25        5.3    132.5
1      Monday       Latte          15        6.0     90.0
2     Tuesday    Espresso          30        5.3    159.0
3     Tuesday       Latte          20        6.0    120.0
4   Wednesday    Espresso          35        5.3    185.5
5   Wednesday       Latte          25        6.0    150.0
6    Thursday    Espresso          40        5.3    212.0
7    Thursday       Latte          30        6.0    180.0
8      Friday    Espresso          45        5.3    238.5
9      Friday       Latte          35        6.0    210.0
10   Saturday    Espresso          45        5.3    238.5
11   Saturday       Latte          35        6.0    210.0
12     Sunday    Espresso          45        5.3    238.5
13     Sunday       Latte          35        6.0    210.0

In [17]:
# semisal kita ingin mengganti nama kolom new_price dengan price
coffe.rename(columns = {'new_price':'price'})

          Day Coffee Type  Units Sold  price  Revenue
0      Monday    Espresso          25    5.3    132.5
1      Monday       Latte          15    6.0     90.0
2     Tuesday    Espresso          30    5.3    159.0
3     Tuesday       Latte          20    6.0    120.0
4   Wednesday    Espresso          35    5.3    185.5
5   Wednesday       Latte          25    6.0    150.0
6    Thursday    Espresso          40    5.3    212.0
7    Thursday       Latte          30    6.0    180.0
8      Friday    Espresso          45    5.3    238.5
9      Friday       Latte          35    6.0    210.0
10   Saturday    Espresso          45    5.3    238.5
11   Saturday       Latte          35    6.0    210.0
12     Sunday    Espresso          45    5.3    238.5
13     Sunday       Latte          35    6.0    210.0

In [18]:
# lagii, jika kita ingin mengubah ini masuk ke dalam dataset kita harus menggunakan salah satu cara dari 2 yang tadi diatas
coffe = coffe.rename(columns = {'new_price':'price'})

In [19]:
coffe

          Day Coffee Type  Units Sold  price  Revenue
0      Monday    Espresso          25    5.3    132.5
1      Monday       Latte          15    6.0     90.0
2     Tuesday    Espresso          30    5.3    159.0
3     Tuesday       Latte          20    6.0    120.0
4   Wednesday    Espresso          35    5.3    185.5
5   Wednesday       Latte          25    6.0    150.0
6    Thursday    Espresso          40    5.3    212.0
7    Thursday       Latte          30    6.0    180.0
8      Friday    Espresso          45    5.3    238.5
9      Friday       Latte          35    6.0    210.0
10   Saturday    Espresso          45    5.3    238.5
11   Saturday       Latte          35    6.0    210.0
12     Sunday    Espresso          45    5.3    238.5
13     Sunday       Latte          35    6.0    210.0

## Bios Dataset for add/remove column example

In [32]:
df_bios = pd.read_csv('data/bios.csv')

In [6]:
# menampilkan 5 baris pertama data
df_bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [7]:
# membuat sebuah kolom dengan label 'first name' yang berfungsi mengisi value nama awal nya saja

# membuat sebuah variabel dengan isi copy an variabel yang sudah di load dataset agar tidak berubah dataset di dalam variabel tersebut

bios_new = df_bios.copy()

In [10]:
# membuat sebuah kolom dengan varibel copy an dari variabel dataset asli
bios_new ['first_name'] = bios_new['name'].str.split(' ').str[0]

In [ ]:
bios_new.head()     # menampilkan 5 data pertama

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Albert

In [ ]:
# mencari nama dengan fungsi query dimana first_name nya yaitu Keith

bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith,Keith
...,...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith,Keith

In [14]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
 10  first name    145500 non-null  object
 11  first_name    145500 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 13.3+ MB

In [15]:
# untuk berurusan dengan sebuah data seperti kolom born_date dimana seharusnya dia sebuah angka atau date kita bisa mengubah nya seperti ini
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [16]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name,first_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,Yuliya,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,André,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,Bill,1913-07-15

In [18]:
# tidak terlihat berbeda namun jika kita melihat dari info nya 
bios_new.info()


# dia akan beruba sebuah datetime dtype nya

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first name     145500 non-null  object
 11  first_name     145500 non-null  object
 12  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(9)
memory usage: 14.4+ MB

In [22]:
# membuat sebuah kolom dengan catatan hanya mengambil tahun dari kelahiran nya saja dengan fungsi pandas yaitu (.dt) ini sama seperti (.str) tetapi dikhususkan untuk tipe data datetime

bios_new['born_year'] = bios_new['born_datetime'].dt.year

bios_new[['name','born_year']]


# jadi fungsi (.dt) ini sangat berguna untuk mengetahui apapun tentang datetime seperti leapyear atau hari pada bulan apa dan apapun

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

Parameter Penting pd.to_datetime():

errors='coerce': Menangani data tidak valid (seperti teks "Unknown") dengan mengubahnya menjadi NaT (Not a Time). Tanpa ini, program akan error jika bertemu data rusak.

format=: Menentukan pola tanggal (misal: %d-%m-%Y untuk 31-12-2024). Penggunaan format spesifik dapat meningkatkan kecepatan proses konversi secara signifikan.

## menyimpan update dataframe kita

In [24]:
bios_new.to_csv('data/bios_new.csv', index=False)

In [25]:
# menampilkan semua kolom di dataset agar tidak bingung atau salah nyebut dengan fungsi info()
df_bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB


Mengelompokkan data numerik height_cm ke dalam 3 kategori label:

Short: Tinggi di bawah 165 cm.

Average: Tinggi antara 165 cm hingga kurang dari 185 cm.

Tall: Tinggi 185 cm ke atas.

In [26]:
# mengkategorikan seseorang berdasarkan tinggi nya [short,average,tall]
df_bios['height_category'] = df_bios['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall'))

In [28]:
df_bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [30]:
# mengkategorikan class atlet seperti [lightweight,middleweight,heavyweight]

# tetapi ini dengan membuat sebuah fungsi 

def categorize_athlete (row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'lightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'middleweight'

    else:
        return 'heavyweight'

df_bios['categorize'] = df_bios.apply(categorize_athlete, axis=1)

In [31]:
df_bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,categorize
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,heavyweight

## Praktek Adding/Removing Columns

In [20]:
# ini merupakan sebuah praktik pribadi tanpa melihat apapun berdasarkan apa yang telah di pelajari di segmentasi ini

# load dataset coffe namun karena sudah ada dan kita tidak mau mengubah nya maka kita akan meload nya dengan variabel baru dengan menggunakan Fungsi .copy()

new_coffee = coffe.copy()

In [21]:
new_coffee.head()

         Day Coffee Type  Units Sold  price  Revenue
0     Monday    Espresso          25    5.3    132.5
1     Monday       Latte          15    6.0     90.0
2    Tuesday    Espresso          30    5.3    159.0
3    Tuesday       Latte          20    6.0    120.0
4  Wednesday    Espresso          35    5.3    185.5

In [22]:
# Membuat sebuah kolom baru bernama total_spent.
new_coffee['total_spent'] = new_coffee['Units Sold'] * new_coffee['price']

In [23]:
new_coffee

          Day Coffee Type  Units Sold  price  Revenue  total_spent
0      Monday    Espresso          25    5.3    132.5        132.5
1      Monday       Latte          15    6.0     90.0         90.0
2     Tuesday    Espresso          30    5.3    159.0        159.0
3     Tuesday       Latte          20    6.0    120.0        120.0
4   Wednesday    Espresso          35    5.3    185.5        185.5
5   Wednesday       Latte          25    6.0    150.0        150.0
6    Thursday    Espresso          40    5.3    212.0        212.0
7    Thursday       Latte          30    6.0    180.0        180.0
8      Friday    Espresso          45    5.3    238.5        238.5
9      Friday       Latte          35    6.0    210.0        210.0
10   Saturday    Espresso          45    5.3    238.5        238.5
11   Saturday       Latte          35    6.0    210.0        210.0
12     Sunday    Espresso          45    5.3    238.5        238.5
13     Sunday       Latte          35    6.0    210.0        210.0

In [24]:
# menghapus kolom revenue dari new_coffe
new_coffee = new_coffee.drop(columns=['Revenue'])

In [25]:
new_coffee

          Day Coffee Type  Units Sold  price  total_spent
0      Monday    Espresso          25    5.3        132.5
1      Monday       Latte          15    6.0         90.0
2     Tuesday    Espresso          30    5.3        159.0
3     Tuesday       Latte          20    6.0        120.0
4   Wednesday    Espresso          35    5.3        185.5
5   Wednesday       Latte          25    6.0        150.0
6    Thursday    Espresso          40    5.3        212.0
7    Thursday       Latte          30    6.0        180.0
8      Friday    Espresso          45    5.3        238.5
9      Friday       Latte          35    6.0        210.0
10   Saturday    Espresso          45    5.3        238.5
11   Saturday       Latte          35    6.0        210.0
12     Sunday    Espresso          45    5.3        238.5
13     Sunday       Latte          35    6.0        210.0

In [26]:
# buat kolom promo_price dimana jika coffee type nya itu espresso maka diskon hingga 2.99 jika bukan maka 5.99

new_coffee['promo_price'] = np.where(new_coffee['Coffee Type'] == 'Espresso',2.99,5.99)

In [27]:
new_coffee

          Day Coffee Type  Units Sold  price  total_spent  promo_price
0      Monday    Espresso          25    5.3        132.5         2.99
1      Monday       Latte          15    6.0         90.0         5.99
2     Tuesday    Espresso          30    5.3        159.0         2.99
3     Tuesday       Latte          20    6.0        120.0         5.99
4   Wednesday    Espresso          35    5.3        185.5         2.99
5   Wednesday       Latte          25    6.0        150.0         5.99
6    Thursday    Espresso          40    5.3        212.0         2.99
7    Thursday       Latte          30    6.0        180.0         5.99
8      Friday    Espresso          45    5.3        238.5         2.99
9      Friday       Latte          35    6.0        210.0         5.99
10   Saturday    Espresso          45    5.3        238.5         2.99
11   Saturday       Latte          35    6.0        210.0         5.99
12     Sunday    Espresso          45    5.3        238.5         2.99
13     Sunday       Latte          35    6.0        210.0         5.99

In [28]:
# mengubah nama kolom Units Sold menjadi jumlah_terjual dan kolom price menjadi harga_satuan 
new_coffee.rename(columns={'Units Sold': 'jumlah_terjual'}, inplace=True)
new_coffee.rename(columns={'price':'harga_satuan'}, inplace=True)

In [29]:
new_coffee

,Day,Coffee Type,jumlah_terjual,harga_satuan,total_spent,promo_price
0,Monday,Espresso,25,5.3,132.5,2.99
1,Monday,Latte,15,6.0,90.0,5.99
2,Tuesday,Espresso,30,5.3,159.0,2.99
3,Tuesday,Latte,20,6.0,120.0,5.99
4,Wednesday,Espresso,35,5.3,185.5,2.99
5,Wednesday,Latte,25,6.0,150.0,5.99
6,Thursday,Espresso,40,5.3,212.0,2.99
7,Thursday,Latte,30,6.0,180.0,5.99
8,Friday,Espresso,45,5.3,238.5,2.99
9,Friday,Latte,35,6.0,210.0,5.99
10,Saturday,Espresso,45,5.3,238.5,2.99
11,Saturday,Latte,35,6.0,210.0,5.99
12,Sunday,Espresso,45,5.3,238.5,2.99
13,Sunday,Latte,35,6.0,210.0,5.99

In [30]:
# menghapus kolom total_spent
new_coffee.drop(columns=['harga_satuan'],inplace=True)

In [31]:
new_coffee

          Day Coffee Type  jumlah_terjual  total_spent  promo_price
0      Monday    Espresso              25        132.5         2.99
1      Monday       Latte              15         90.0         5.99
2     Tuesday    Espresso              30        159.0         2.99
3     Tuesday       Latte              20        120.0         5.99
4   Wednesday    Espresso              35        185.5         2.99
5   Wednesday       Latte              25        150.0         5.99
6    Thursday    Espresso              40        212.0         2.99
7    Thursday       Latte              30        180.0         5.99
8      Friday    Espresso              45        238.5         2.99
9      Friday       Latte              35        210.0         5.99
10   Saturday    Espresso              45        238.5         2.99
11   Saturday       Latte              35        210.0         5.99
12     Sunday    Espresso              45        238.5         2.99
13     Sunday       Latte              35        210.0         5.99

In [32]:
# membuat sebuah kolom status_penjualan 

new_coffee['status_penjualan'] = np.where(new_coffee['jumlah_terjual'] > 25, "Target Achieved", "Under Performance")

In [33]:
new_coffee

,Day,Coffee Type,jumlah_terjual,total_spent,promo_price,status_penjualan
0,Monday,Espresso,25,132.5,2.99,Under Performance
1,Monday,Latte,15,90.0,5.99,Under Performance
2,Tuesday,Espresso,30,159.0,2.99,Target Achieved
3,Tuesday,Latte,20,120.0,5.99,Under Performance
4,Wednesday,Espresso,35,185.5,2.99,Target Achieved
5,Wednesday,Latte,25,150.0,5.99,Under Performance
6,Thursday,Espresso,40,212.0,2.99,Target Achieved
7,Thursday,Latte,30,180.0,5.99,Target Achieved
8,Friday,Espresso,45,238.5,2.99,Target Achieved
9,Friday,Latte,35,210.0,5.99,Target Achieved
10,Saturday,Espresso,45,238.5,2.99,Target Achieved
11,Saturday,Latte,35,210.0,5.99,Target Achieved
12,Sunday,Espresso,45,238.5,2.99,Target Achieved
13,Sunday,Latte,35,210.0,5.99,Target Achieved

In [34]:
# membuat sebuah kolom tax_amount dengan isi 10% dari pajak
new_coffee['tax_amount'] = new_coffee['promo_price'] * 10/100

In [35]:
new_coffee

,Day,Coffee Type,jumlah_terjual,total_spent,promo_price,status_penjualan,tax_amount
0,Monday,Espresso,25,132.5,2.99,Under Performance,0.299
1,Monday,Latte,15,90.0,5.99,Under Performance,0.599
2,Tuesday,Espresso,30,159.0,2.99,Target Achieved,0.299
3,Tuesday,Latte,20,120.0,5.99,Under Performance,0.599
4,Wednesday,Espresso,35,185.5,2.99,Target Achieved,0.299
5,Wednesday,Latte,25,150.0,5.99,Under Performance,0.599
6,Thursday,Espresso,40,212.0,2.99,Target Achieved,0.299
7,Thursday,Latte,30,180.0,5.99,Target Achieved,0.599
8,Friday,Espresso,45,238.5,2.99,Target Achieved,0.299
9,Friday,Latte,35,210.0,5.99,Target Achieved,0.599
10,Saturday,Espresso,45,238.5,2.99,Target Achieved,0.299
11,Saturday,Latte,35,210.0,5.99,Target Achieved,0.599
12,Sunday,Espresso,45,238.5,2.99,Target Achieved,0.299
13,Sunday,Latte,35,210.0,5.99,Target Achieved,0.599

In [36]:
# mengubah kolom Coffee type menjadi jenis_kopi

new_coffee.rename(columns={'Coffee Type':'jenis_kopi'}, inplace=True)

In [37]:
new_coffee

,Day,jenis_kopi,jumlah_terjual,total_spent,promo_price,status_penjualan,tax_amount
0,Monday,Espresso,25,132.5,2.99,Under Performance,0.299
1,Monday,Latte,15,90.0,5.99,Under Performance,0.599
2,Tuesday,Espresso,30,159.0,2.99,Target Achieved,0.299
3,Tuesday,Latte,20,120.0,5.99,Under Performance,0.599
4,Wednesday,Espresso,35,185.5,2.99,Target Achieved,0.299
5,Wednesday,Latte,25,150.0,5.99,Under Performance,0.599
6,Thursday,Espresso,40,212.0,2.99,Target Achieved,0.299
7,Thursday,Latte,30,180.0,5.99,Target Achieved,0.599
8,Friday,Espresso,45,238.5,2.99,Target Achieved,0.299
9,Friday,Latte,35,210.0,5.99,Target Achieved,0.599
10,Saturday,Espresso,45,238.5,2.99,Target Achieved,0.299
11,Saturday,Latte,35,210.0,5.99,Target Achieved,0.599
12,Sunday,Espresso,45,238.5,2.99,Target Achieved,0.299
13,Sunday,Latte,35,210.0,5.99,Target Achieved,0.599

In [38]:
# membuat sebuah kolom baru bernama final_price dengan isi promo_price + tax_amount
new_coffee['final_price'] = new_coffee['promo_price'] + new_coffee['tax_amount']

In [39]:
new_coffee

,Day,jenis_kopi,jumlah_terjual,total_spent,promo_price,status_penjualan,tax_amount,final_price
0,Monday,Espresso,25,132.5,2.99,Under Performance,0.299,3.289
1,Monday,Latte,15,90.0,5.99,Under Performance,0.599,6.589
2,Tuesday,Espresso,30,159.0,2.99,Target Achieved,0.299,3.289
3,Tuesday,Latte,20,120.0,5.99,Under Performance,0.599,6.589
4,Wednesday,Espresso,35,185.5,2.99,Target Achieved,0.299,3.289
5,Wednesday,Latte,25,150.0,5.99,Under Performance,0.599,6.589
6,Thursday,Espresso,40,212.0,2.99,Target Achieved,0.299,3.289
7,Thursday,Latte,30,180.0,5.99,Target Achieved,0.599,6.589
8,Friday,Espresso,45,238.5,2.99,Target Achieved,0.299,3.289
9,Friday,Latte,35,210.0,5.99,Target Achieved,0.599,6.589
10,Saturday,Espresso,45,238.5,2.99,Target Achieved,0.299,3.289
11,Saturday,Latte,35,210.0,5.99,Target Achieved,0.599,6.589
12,Sunday,Espresso,45,238.5,2.99,Target Achieved,0.299,3.289
13,Sunday,Latte,35,210.0,5.99,Target Achieved,0.599,6.589

In [40]:
# testing github

# praktek 2 (Fraud Analytics Challenge)

In [39]:
# load dataset 

cc_fraud = pd.read_csv('data/credit_card_fraud_dataset.csv')

In [40]:
cc_fraud.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0

In [ ]:
# ubah TransactionDate menjadi datetime
cc_fraud['TransactionDate'] = pd.to_datetime(cc_fraud['TransactionDate'], errors='coerce')

cc_fraud.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0

In [ ]:
# info apakah sudah terubah dtype nya menjadi datetime.
cc_fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   TransactionID    100000 non-null  int64
 1   TransactionDate  100000 non-null  datetime64[ns]
 2   Amount           100000 non-null  float64
 3   MerchantID       100000 non-null  int64
 4   TransactionType  100000 non-null  object
 5   Location         100000 non-null  object
 6   IsFraud          100000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 5.3+ MB

In [47]:
# membuat sebuah kolom HourofDay dan kolom DayofWeek.

cc_fraud['HourofDay'] = cc_fraud['TransactionDate'].dt.hour
cc_fraud['DayofWeek'] = cc_fraud['TransactionDate'].dt.day_of_week
cc_fraud.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4

In [59]:
# membuat sebuah kolom boolean Is_Night_Transaction yang bernilai True jika transaksi terjadi antara jam 00:00 hingga 05:00 pagi (waktu rawan fraud).

cc_fraud['Is_Night_Transaction'] = cc_fraud['HourofDay'] < 6
cc_fraud.head(10)

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2,False
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1,False
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0,False
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5,False
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4,False
5,6,2024-08-30 01:52:35.462867,3086.22,302,purchase,New York,0,1,4,True
6,7,2024-01-02 11:31:35.462875,1466.90,902,refund,Philadelphia,0,11,1,False
7,8,2024-05-12 12:25:35.462885,917.21,266,purchase,New York,0,12,6,False
8,9,2023-11-16 02:20:35.462894,1625.73,32,refund,Chicago,0,2,3,True
9,10,2023-10-24 06:51:35.462901,662.07,193,purchase,Dallas,0,6,1,False

In [ ]:
# membuat sebuah  kolom Risk_Level dengan kategori Critical, Medium, Low
cc_fraud['Risk_Level'] = np.where((cc_fraud['Amount'] > 4000) & (cc_fraud['TransactionType'] == "refund"), 'Critical', np.where(cc_fraud['Amount'].between(2000,4000),'Medium','Low'))

In [63]:
cc_fraud.head(10)

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2,False,Critical
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1,False,Medium
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0,False,Low
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5,False,Medium
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4,False,Low
5,6,2024-08-30 01:52:35.462867,3086.22,302,purchase,New York,0,1,4,True,Medium
6,7,2024-01-02 11:31:35.462875,1466.90,902,refund,Philadelphia,0,11,1,False,Low
7,8,2024-05-12 12:25:35.462885,917.21,266,purchase,New York,0,12,6,False,Low
8,9,2023-11-16 02:20:35.462894,1625.73,32,refund,Chicago,0,2,3,True,Low
9,10,2023-10-24 06:51:35.462901,662.07,193,purchase,Dallas,0,6,1,False,Low

In [80]:
# Buat kolom Flag_Suspicious.
# Berikan nilai 1 jika transaksi terjadi di 'New York' atau 'Houston' dengan Amount di atas rata-rata (mean) seluruh transaksi, jika tidak 0.

# membuat fungsi mean dari amount 
def flag_Suspicious(row):
    if (row['Location'] in ["New York","Houston"]) and (row['Amount'] > np.mean(cc_fraud['Amount'])):
        return 1
    else:
        return 0

            
        
    

cc_fraud['Flag_Suspicious'] = cc_fraud.apply(flag_Suspicious, axis=1)

In [ ]:
# Sebenarnya, untuk kasus ini, penggunaan .apply(axis=1) dianggap lambat di industri jika datanya jutaan. Cara tercepat adalah menggunakan np.where atau logika Boolean:

# mean_amount = cc_fraud['Amount'].mean()

# # Cara yang jauh lebih cepat (Vectorized)
# cc_fraud['Flag_Suspicious'] = np.where(
#     (cc_fraud['Location'].isin(["New York", "Houston"])) & (cc_fraud['Amount'] > mean_amount),
#     1, 
#     0
# )

In [81]:
cc_fraud

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level,Flag_Suspicious
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,14,2,False,Critical,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,13,1,False,Medium,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,10,0,False,Low,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,23,5,False,Medium,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,18,4,False,Low,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,2024-06-07 00:57:36.027591,1057.29,289,refund,San Antonio,0,0,4,True,Low,0
99996,99997,2023-10-22 23:12:36.027594,297.25,745,refund,San Antonio,0,23,6,False,Low,0
99997,99998,2024-05-31 19:27:36.027597,3448.56,690,purchase,San Antonio,0,19,4,False,Medium,0
99998,99999,2024-10-18 09:43:36.027601,3750.79,644,purchase,Philadelphia,0,9,4,False,Medium,0
99999,100000,2024-03-05 19:41:36.027606,1596.79,675,refund,Houston,0,19,1,False,Low,0

In [ ]:
cc_fraud.query('Flag_Suspicious == 1') # menampilkan data dengan suspecious 1

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,HourofDay,DayofWeek,Is_Night_Transaction,Risk_Level,Flag_Suspicious
5,6,2024-08-30 01:52:35.462867,3086.22,302,purchase,New York,0,1,4,True,Medium,1
12,13,2024-08-31 02:38:35.462922,2855.69,219,refund,New York,0,2,5,True,Medium,1
16,17,2024-01-04 22:23:35.462948,2721.95,912,refund,New York,0,22,3,False,Medium,1
26,27,2024-09-22 11:17:35.463015,4186.42,725,purchase,New York,0,11,6,False,Low,1
38,39,2024-08-09 09:02:35.463100,3204.04,663,purchase,Houston,0,9,4,False,Medium,1
...,...,...,...,...,...,...,...,...,...,...,...,...
99965,99966,2023-11-14 05:36:36.027463,3468.88,437,refund,Houston,0,5,1,True,Medium,1
99976,99977,2024-06-23 11:12:36.027527,2961.80,866,refund,Houston,0,11,6,False,Medium,1
99977,99978,2023-11-23 04:08:36.027530,2690.97,541,refund,New York,0,4,3,True,Medium,1
99987,99988,2024-07-20 13:42:36.027564,4778.32,767,refund,New York,0,13,5,False,Critical,1
99990,99991,2024-01-12 17:50:36.027574,2883.93,231,refund,New York,0,17,4,False,Medium,1