# Advanced Functionality

In [1]:
# Import Library
import pandas as pd
import numpy as np

In [13]:
# Load Dataframe Coffee

coffee = pd.read_csv('data/coffee_update.csv')
bios = pd.read_csv('data/bios.csv')

In [14]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso   15.000000   3.99    99.75
1     Monday       Latte   15.000000   5.99    89.85
2    Tuesday    Espresso   21.666667   3.99   119.70
3    Tuesday       Latte   28.333333   5.99   119.80
4  Wednesday    Espresso   35.000000   3.99   139.65

### Fungsi .shift()
Secara sederhana, fungsi ini digunakan untuk menggeser data ke atas atau ke bawah pada indeks tertentu.

In [15]:
# test fungsi .shift()

# membuat kolom baru dengan isi pendapatan kemarin 

coffee['yesterday_revenue'] = coffee['revenue'].shift(2)

In [16]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0     Monday    Espresso   15.000000   3.99    99.75                NaN
1     Monday       Latte   15.000000   5.99    89.85                NaN
2    Tuesday    Espresso   21.666667   3.99   119.70              99.75
3    Tuesday       Latte   28.333333   5.99   119.80              89.85
4  Wednesday    Espresso   35.000000   3.99   139.65             119.70

In [17]:
# membuat pertumbuhan persen

coffee['pct_change'] = coffee['revenue'] / coffee['yesterday_revenue'] * 100

In [18]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,15.000000,3.99,99.75,NaN,NaN
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,21.666667,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000

### Fungsi .rank()
Fungsi ini digunakan untuk memberikan peringkat atau posisi pada setiap elemen dalam kumpulan data.

In [83]:
# contoh fungsi .rank()

# menerapkan rank dari tinggi suatu atlet 
bios['height_rank'] = bios['height_cm'].rank(ascending=False)

In [85]:
# menerapkan sort values dari terbesar ke terkecil
bios.sort_values(['height_rank'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,2.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,2.5
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,5.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,NaN

In [65]:
# menampilkan 10 sample dengan mengambil kolom nama dan rank
bios.sort_values(['height_rank']).sample(10)[['name','height_rank']]

                      name  height_rank
73322        Anton Toscani          NaN
74520   Faraj Saad Marzouk      58380.5
63512     Harry Van Bergen          NaN
47151          Karla Linke      38677.0
121141    Abdelhak Aatakni          NaN
129287  Şebnem Kimyacıoğlu      31471.5
80823     Jeanette Kessler          NaN
102362        Kiera Aitken      87188.5
11619         Hans Brugman      69980.5
43891     Anders Kvissberg      46966.0

### Fungsi .rolling()
.rolling() adalah tentang melihat gambaran besar melalui "jendela" yang bergerak.

In [66]:
# menggunakan fungi .rolling()

coffee['cumulative_revenue'] = coffee['revenue'].cumsum()

In [67]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,15.000000,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,21.666667,3.99,119.70,99.75,120.000000,309.30
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.10
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667,568.75
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.50
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714,878.10
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.80
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000,1237.35
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.00
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000,1626.55
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.20
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000,2015.75
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.40

In [68]:
# meng copy data hanya berisi tipe kopi latte dan menghtung kumulatif pendapatan nya per 3 hari menggunakan rolling

latte = coffee[coffee['Coffee Type'] == "Latte"].copy()
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.6
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.1
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.5
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.8
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.0
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.2
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.4

In [69]:
latte['3day'] = latte['Units Sold'].rolling(3).sum()

In [70]:
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3day
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.1,NaN
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.5,68.333333
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.8,83.333333
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.0,90.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.2,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.4,105.000000

## kita ingin tahu versi pandas kita untuk mengganti backend nya dari numpy menjadi pyarrow

In [71]:
pd.__version__

'2.3.3'

### apa itu pyarrow?

PyArrow adalah library Python yang menjadi jembatan untuk Apache Arrow, sebuah platform pengembangan lintas bahasa untuk data dalam memori (in-memory data).

PyArrow adalah sebuah pustaka (library) Python yang berfungsi sebagai "mesin penggerak" atau jembatan canggih untuk mengolah data dalam jumlah sangat besar dengan kecepatan tinggi. Bayangkan PyArrow sebagai sistem pengorganisasian data yang sangat rapi di dalam memori komputer, di mana data tidak disimpan baris demi baris seperti daftar belanjaan biasa, melainkan dikelompokkan berdasarkan kolomnya. Cara penyimpanan secara kolom ini membuat komputer jauh lebih cerdas dan efisien saat melakukan perhitungan atau pencarian, karena ia hanya perlu membaca kolom yang benar-benar dibutuhkan tanpa membuang-buang tenaga untuk memproses data yang tidak relevan.

In [72]:

# cara penggunaan pyarrow dengan syarat versi pandas diatas 2
bios_numpy = pd.read_csv('data/bios.csv')
bios_pyarrow = pd.read_csv('data/bios.csv', dtype_backend='pyarrow', engine='pyarrow')

In [73]:
bios_numpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [74]:
bios_pyarrow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64[pyarrow]
 1   name          145500 non-null  string[pyarrow]
 2   born_date     143693 non-null  date32[day][pyarrow]
 3   born_city     110908 non-null  string[pyarrow]
 4   born_region   110908 non-null  string[pyarrow]
 5   born_country  110908 non-null  string[pyarrow]
 6   NOC           145499 non-null  string[pyarrow]
 7   height_cm     106651 non-null  double[pyarrow]
 8   weight_kg     102070 non-null  double[pyarrow]
 9   died_date     33940 non-null   date32[day][pyarrow]
dtypes: date32[day][pyarrow](2), double[pyarrow](2), int64[pyarrow](1), string[pyarrow](5)
memory usage: 13.0 MB

In [75]:
import pandas as pd
import numpy as np

# Membuat data dummy trading
data = {
    'Tanggal': pd.to_datetime(['2024-05-01', '2024-05-02', '2024-05-03', '2024-05-04', '2024-05-05'] * 3),
    'Aset': ['BTC']*5 + ['ETH']*5 + ['SOL']*5,
    'Harga_Close': [60000, 62000, 61000, 63000, 64000,  # BTC
                    3000, 3100, 2900, 3200, 3300,      # ETH
                    140, 150, 145, 160, 155]           # SOL
}

df = pd.DataFrame(data)
# Mengurutkan data berdasarkan Aset dan Tanggal agar logikanya benar
df = df.sort_values(by=['Aset', 'Tanggal']).reset_index(drop=True)
print("Dataset Siap!")
print(df.head(10))

Dataset Siap!
     Tanggal Aset  Harga_Close
0 2024-05-01  BTC        60000
1 2024-05-02  BTC        62000
2 2024-05-03  BTC        61000
3 2024-05-04  BTC        63000
4 2024-05-05  BTC        64000
5 2024-05-01  ETH         3000
6 2024-05-02  ETH         3100
7 2024-05-03  ETH         2900
8 2024-05-04  ETH         3200
9 2024-05-05  ETH         3300

In [76]:
df

      Tanggal Aset  Harga_Close
0  2024-05-01  BTC        60000
1  2024-05-02  BTC        62000
2  2024-05-03  BTC        61000
3  2024-05-04  BTC        63000
4  2024-05-05  BTC        64000
5  2024-05-01  ETH         3000
6  2024-05-02  ETH         3100
7  2024-05-03  ETH         2900
8  2024-05-04  ETH         3200
9  2024-05-05  ETH         3300
10 2024-05-01  SOL          140
11 2024-05-02  SOL          150
12 2024-05-03  SOL          145
13 2024-05-04  SOL          160
14 2024-05-05  SOL          155

In [77]:
df['Harga_Kemarin'] = df.groupby(['Aset'])['Harga_Close'].shift(1)

In [78]:
df

      Tanggal Aset  Harga_Close  Harga_Kemarin
0  2024-05-01  BTC        60000            NaN
1  2024-05-02  BTC        62000        60000.0
2  2024-05-03  BTC        61000        62000.0
3  2024-05-04  BTC        63000        61000.0
4  2024-05-05  BTC        64000        63000.0
5  2024-05-01  ETH         3000            NaN
6  2024-05-02  ETH         3100         3000.0
7  2024-05-03  ETH         2900         3100.0
8  2024-05-04  ETH         3200         2900.0
9  2024-05-05  ETH         3300         3200.0
10 2024-05-01  SOL          140            NaN
11 2024-05-02  SOL          150          140.0
12 2024-05-03  SOL          145          150.0
13 2024-05-04  SOL          160          145.0
14 2024-05-05  SOL          155          160.0

In [79]:
df['Perubahan_harga'] = df['Harga_Close'] - df['Harga_Kemarin']

In [80]:
df

      Tanggal Aset  Harga_Close  Harga_Kemarin  Perubahan_harga
0  2024-05-01  BTC        60000            NaN              NaN
1  2024-05-02  BTC        62000        60000.0           2000.0
2  2024-05-03  BTC        61000        62000.0          -1000.0
3  2024-05-04  BTC        63000        61000.0           2000.0
4  2024-05-05  BTC        64000        63000.0           1000.0
5  2024-05-01  ETH         3000            NaN              NaN
6  2024-05-02  ETH         3100         3000.0            100.0
7  2024-05-03  ETH         2900         3100.0           -200.0
8  2024-05-04  ETH         3200         2900.0            300.0
9  2024-05-05  ETH         3300         3200.0            100.0
10 2024-05-01  SOL          140            NaN              NaN
11 2024-05-02  SOL          150          140.0             10.0
12 2024-05-03  SOL          145          150.0             -5.0
13 2024-05-04  SOL          160          145.0             15.0
14 2024-05-05  SOL          155          160.0             -5.0

In [93]:
df['rank'] = df['Harga_Close'].rank(method='dense',ascending=False)

In [94]:
df.sort_values(['rank'])

      Tanggal Aset  Harga_Close  Harga_Kemarin  Perubahan_harga  rank
4  2024-05-05  BTC        64000        63000.0           1000.0   1.0
3  2024-05-04  BTC        63000        61000.0           2000.0   2.0
1  2024-05-02  BTC        62000        60000.0           2000.0   3.0
2  2024-05-03  BTC        61000        62000.0          -1000.0   4.0
0  2024-05-01  BTC        60000            NaN              NaN   5.0
9  2024-05-05  ETH         3300         3200.0            100.0   6.0
8  2024-05-04  ETH         3200         2900.0            300.0   7.0
6  2024-05-02  ETH         3100         3000.0            100.0   8.0
5  2024-05-01  ETH         3000            NaN              NaN   9.0
7  2024-05-03  ETH         2900         3100.0           -200.0  10.0
13 2024-05-04  SOL          160          145.0             15.0  11.0
14 2024-05-05  SOL          155          160.0             -5.0  12.0
11 2024-05-02  SOL          150          140.0             10.0  13.0
12 2024-05-03  SOL          145          150.0             -5.0  14.0
10 2024-05-01  SOL          140            NaN              NaN  15.0

In [104]:
df['SMA_3'] = df.groupby(['Aset'])['Harga_Close'].rolling(3,min_periods=1).mean().reset_index(0, drop=True)

In [105]:
df

,Tanggal,Aset,Harga_Close,Harga_Kemarin,Perubahan_harga,rank,SMA_3,standart_deviasi
0,2024-05-01,BTC,60000,NaN,NaN,5.0,60000.000000,NaN
1,2024-05-02,BTC,62000,60000.0,2000.0,3.0,61000.000000,NaN
2,2024-05-03,BTC,61000,62000.0,-1000.0,4.0,61000.000000,1000.000000
3,2024-05-04,BTC,63000,61000.0,2000.0,2.0,62000.000000,1000.000000
4,2024-05-05,BTC,64000,63000.0,1000.0,1.0,62666.666667,1527.525232
5,2024-05-01,ETH,3000,NaN,NaN,9.0,3000.000000,NaN
6,2024-05-02,ETH,3100,3000.0,100.0,8.0,3050.000000,NaN
7,2024-05-03,ETH,2900,3100.0,-200.0,10.0,3000.000000,100.000000
8,2024-05-04,ETH,3200,2900.0,300.0,7.0,3066.666667,152.752523
9,2024-05-05,ETH,3300,3200.0,100.0,6.0,3133.333333,208.166600
10,2024-05-01,SOL,140,NaN,NaN,15.0,140.000000,NaN
11,2024-05-02,SOL,150,140.0,10.0,13.0,145.000000,NaN
12,2024-05-03,SOL,145,150.0,-5.0,14.0,145.000000,5.000000
13,2024-05-04,SOL,160,145.0,15.0,11.0,151.666667,7.637626
14,2024-05-05,SOL,155,160.0,-5.0,12.0,153.333333,7.637626

In [106]:
df['standart_deviasi'] = df.groupby(['Aset'])['Harga_Close'].rolling(3).std().reset_index(0, drop=True)

In [107]:
df

,Tanggal,Aset,Harga_Close,Harga_Kemarin,Perubahan_harga,rank,SMA_3,standart_deviasi
0,2024-05-01,BTC,60000,NaN,NaN,5.0,60000.000000,NaN
1,2024-05-02,BTC,62000,60000.0,2000.0,3.0,61000.000000,NaN
2,2024-05-03,BTC,61000,62000.0,-1000.0,4.0,61000.000000,1000.000000
3,2024-05-04,BTC,63000,61000.0,2000.0,2.0,62000.000000,1000.000000
4,2024-05-05,BTC,64000,63000.0,1000.0,1.0,62666.666667,1527.525232
5,2024-05-01,ETH,3000,NaN,NaN,9.0,3000.000000,NaN
6,2024-05-02,ETH,3100,3000.0,100.0,8.0,3050.000000,NaN
7,2024-05-03,ETH,2900,3100.0,-200.0,10.0,3000.000000,100.000000
8,2024-05-04,ETH,3200,2900.0,300.0,7.0,3066.666667,152.752523
9,2024-05-05,ETH,3300,3200.0,100.0,6.0,3133.333333,208.166600
10,2024-05-01,SOL,140,NaN,NaN,15.0,140.000000,NaN
11,2024-05-02,SOL,150,140.0,10.0,13.0,145.000000,NaN
12,2024-05-03,SOL,145,150.0,-5.0,14.0,145.000000,5.000000
13,2024-05-04,SOL,160,145.0,15.0,11.0,151.666667,7.637626
14,2024-05-05,SOL,155,160.0,-5.0,12.0,153.333333,7.637626

In [110]:
df['Harga_Besok'] = df.groupby(['Aset'])['Harga_Close'].shift(-1)

In [111]:
df

,Tanggal,Aset,Harga_Close,Harga_Kemarin,Perubahan_harga,rank,SMA_3,standart_deviasi,Harga_Besok
0,2024-05-01,BTC,60000,NaN,NaN,5.0,60000.000000,NaN,62000.0
1,2024-05-02,BTC,62000,60000.0,2000.0,3.0,61000.000000,NaN,61000.0
2,2024-05-03,BTC,61000,62000.0,-1000.0,4.0,61000.000000,1000.000000,63000.0
3,2024-05-04,BTC,63000,61000.0,2000.0,2.0,62000.000000,1000.000000,64000.0
4,2024-05-05,BTC,64000,63000.0,1000.0,1.0,62666.666667,1527.525232,NaN
5,2024-05-01,ETH,3000,NaN,NaN,9.0,3000.000000,NaN,3100.0
6,2024-05-02,ETH,3100,3000.0,100.0,8.0,3050.000000,NaN,2900.0
7,2024-05-03,ETH,2900,3100.0,-200.0,10.0,3000.000000,100.000000,3200.0
8,2024-05-04,ETH,3200,2900.0,300.0,7.0,3066.666667,152.752523,3300.0
9,2024-05-05,ETH,3300,3200.0,100.0,6.0,3133.333333,208.166600,NaN
10,2024-05-01,SOL,140,NaN,NaN,15.0,140.000000,NaN,150.0
11,2024-05-02,SOL,150,140.0,10.0,13.0,145.000000,NaN,145.0
12,2024-05-03,SOL,145,150.0,-5.0,14.0,145.000000,5.000000,160.0
13,2024-05-04,SOL,160,145.0,15.0,11.0,151.666667,7.637626,155.0
14,2024-05-05,SOL,155,160.0,-5.0,12.0,153.333333,7.637626,NaN

In [114]:
df ['signal'] = df['Harga_Close']<df['Harga_Besok']

In [115]:
df

,Tanggal,Aset,Harga_Close,Harga_Kemarin,Perubahan_harga,rank,SMA_3,standart_deviasi,Harga_Besok,signal
0,2024-05-01,BTC,60000,NaN,NaN,5.0,60000.000000,NaN,62000.0,True
1,2024-05-02,BTC,62000,60000.0,2000.0,3.0,61000.000000,NaN,61000.0,False
2,2024-05-03,BTC,61000,62000.0,-1000.0,4.0,61000.000000,1000.000000,63000.0,True
3,2024-05-04,BTC,63000,61000.0,2000.0,2.0,62000.000000,1000.000000,64000.0,True
4,2024-05-05,BTC,64000,63000.0,1000.0,1.0,62666.666667,1527.525232,NaN,False
5,2024-05-01,ETH,3000,NaN,NaN,9.0,3000.000000,NaN,3100.0,True
6,2024-05-02,ETH,3100,3000.0,100.0,8.0,3050.000000,NaN,2900.0,False
7,2024-05-03,ETH,2900,3100.0,-200.0,10.0,3000.000000,100.000000,3200.0,True
8,2024-05-04,ETH,3200,2900.0,300.0,7.0,3066.666667,152.752523,3300.0,True
9,2024-05-05,ETH,3300,3200.0,100.0,6.0,3133.333333,208.166600,NaN,False
10,2024-05-01,SOL,140,NaN,NaN,15.0,140.000000,NaN,150.0,True
11,2024-05-02,SOL,150,140.0,10.0,13.0,145.000000,NaN,145.0,False
12,2024-05-03,SOL,145,150.0,-5.0,14.0,145.000000,5.000000,160.0,True
13,2024-05-04,SOL,160,145.0,15.0,11.0,151.666667,7.637626,155.0,False
14,2024-05-05,SOL,155,160.0,-5.0,12.0,153.333333,7.637626,NaN,False

In [117]:
df['percentil_harga'] = df.groupby(['Aset'])['Harga_Close'].rank(pct=True)

In [118]:
df

,Tanggal,Aset,Harga_Close,Harga_Kemarin,Perubahan_harga,rank,SMA_3,standart_deviasi,Harga_Besok,signal,percentil_harga
0,2024-05-01,BTC,60000,NaN,NaN,5.0,60000.000000,NaN,62000.0,True,0.2
1,2024-05-02,BTC,62000,60000.0,2000.0,3.0,61000.000000,NaN,61000.0,False,0.6
2,2024-05-03,BTC,61000,62000.0,-1000.0,4.0,61000.000000,1000.000000,63000.0,True,0.4
3,2024-05-04,BTC,63000,61000.0,2000.0,2.0,62000.000000,1000.000000,64000.0,True,0.8
4,2024-05-05,BTC,64000,63000.0,1000.0,1.0,62666.666667,1527.525232,NaN,False,1.0
5,2024-05-01,ETH,3000,NaN,NaN,9.0,3000.000000,NaN,3100.0,True,0.4
6,2024-05-02,ETH,3100,3000.0,100.0,8.0,3050.000000,NaN,2900.0,False,0.6
7,2024-05-03,ETH,2900,3100.0,-200.0,10.0,3000.000000,100.000000,3200.0,True,0.2
8,2024-05-04,ETH,3200,2900.0,300.0,7.0,3066.666667,152.752523,3300.0,True,0.8
9,2024-05-05,ETH,3300,3200.0,100.0,6.0,3133.333333,208.166600,NaN,False,1.0
10,2024-05-01,SOL,140,NaN,NaN,15.0,140.000000,NaN,150.0,True,0.2
11,2024-05-02,SOL,150,140.0,10.0,13.0,145.000000,NaN,145.0,False,0.6
12,2024-05-03,SOL,145,150.0,-5.0,14.0,145.000000,5.000000,160.0,True,0.4
13,2024-05-04,SOL,160,145.0,15.0,11.0,151.666667,7.637626,155.0,False,1.0
14,2024-05-05,SOL,155,160.0,-5.0,12.0,153.333333,7.637626,NaN,False,0.8

In [119]:
# --- CHALLENGE 9: CROSS-SECTIONAL RANKING (MOMENTUM) ---

# 1. Mencari tanggal terakhir secara otomatis
tanggal_terakhir = df['Tanggal'].max()

# 2. Memfilter data agar hanya berisi baris di tanggal terakhir
# Kita gunakan .copy() agar tidak muncul peringatan SettingWithCopyWarning
df_akhir = df[df['Tanggal'] == tanggal_terakhir].copy()

# 3. Melakukan ranking antar aset berdasarkan kolom SMA_3
# ascending=False -> Nilai SMA tertinggi (tren paling kuat) jadi Nomor 1
df_akhir['Rank_Trend'] = df_akhir['SMA_3'].rank(ascending=False)

# Menampilkan hasil pemenang momentum di hari terakhir
print(f"Hasil Momentum pada Tanggal: {tanggal_terakhir.date()}")
print(df_akhir[['Aset', 'SMA_3', 'Rank_Trend']].sort_values(by='Rank_Trend'))

Hasil Momentum pada Tanggal: 2024-05-05
   Aset         SMA_3  Rank_Trend
4   BTC  62666.666667         1.0
9   ETH   3133.333333         2.0
14  SOL    153.333333         3.0

In [121]:
df_arrow = df.convert_dtypes(dtype_backend='pyarrow')

In [122]:
df_arrow

,Tanggal,Aset,Harga_Close,Harga_Kemarin,Perubahan_harga,rank,SMA_3,standart_deviasi,Harga_Besok,signal,percentil_harga
0,2024-05-01 00:00:00,BTC,60000,<NA>,<NA>,5,60000.0,<NA>,62000,True,0.2
1,2024-05-02 00:00:00,BTC,62000,60000,2000,3,61000.0,<NA>,61000,False,0.6
2,2024-05-03 00:00:00,BTC,61000,62000,-1000,4,61000.0,1000.0,63000,True,0.4
3,2024-05-04 00:00:00,BTC,63000,61000,2000,2,62000.0,1000.0,64000,True,0.8
4,2024-05-05 00:00:00,BTC,64000,63000,1000,1,62666.666667,1527.525232,<NA>,False,1.0
5,2024-05-01 00:00:00,ETH,3000,<NA>,<NA>,9,3000.0,<NA>,3100,True,0.4
6,2024-05-02 00:00:00,ETH,3100,3000,100,8,3050.0,<NA>,2900,False,0.6
7,2024-05-03 00:00:00,ETH,2900,3100,-200,10,3000.0,100.0,3200,True,0.2
8,2024-05-04 00:00:00,ETH,3200,2900,300,7,3066.666667,152.752523,3300,True,0.8
9,2024-05-05 00:00:00,ETH,3300,3200,100,6,3133.333333,208.1666,<NA>,False,1.0
10,2024-05-01 00:00:00,SOL,140,<NA>,<NA>,15,140.0,<NA>,150,True,0.2
11,2024-05-02 00:00:00,SOL,150,140,10,13,145.0,<NA>,145,False,0.6
12,2024-05-03 00:00:00,SOL,145,150,-5,14,145.0,5.0,160,True,0.4
13,2024-05-04 00:00:00,SOL,160,145,15,11,151.666667,7.637626,155,False,1.0
14,2024-05-05 00:00:00,SOL,155,160,-5,12,153.333333,7.637626,<NA>,False,0.8