# Aggregating Data

proses menggabungkan, mengelompokkan, atau meringkas banyak baris data menjadi satu nilai ringkasan yang bermakna. Tujuan utamanya adalah untuk melihat pola besar dari dataset, bukan hanya melihat baris data satu per satu.

In [15]:
# import library 

import pandas as pd
import numpy as np

In [16]:
# Load dataframe

# Dataframe Bios
bios = pd.read_csv('data/bios.csv')

# Dataframe coffe
coffee = pd.read_csv('data/coffee_update.csv')

In [17]:
# melihat jumlah orang yang lahir di tempat yang sama berdasarkan kolom 'born_city'

bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Bodrogkisfalud        1
Ternberg              1
Klaus                 1
Plaški                1
Dulwich Hill          1
Name: count, Length: 22368, dtype: int64

In [18]:
# melihat info jumlah orang yang berada di amerika berdasarkan region yang sama
bios[bios['born_country'] == "USA"]['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
South Carolina            50
Maine                     50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [19]:
# melihat info jumlah orang yang berada di amerika berdasarkan region yang sama dari urutan belakang atau terkecil 

bios[bios['born_country'] == "USA"]['born_region'].value_counts().tail(25)

born_region
Utah              91
Missouri          91
North Carolina    86
Arizona           83
New Hampshire     83
Vermont           68
Mississippi       66
Alabama           64
Kentucky          62
Tennessee         62
Nebraska          60
Rhode Island      56
Montana           55
South Carolina    50
Maine             50
Alaska            45
Arkansas          42
Idaho             41
New Mexico        38
Nevada            36
South Dakota      27
West Virginia     24
Delaware          22
North Dakota      16
Wyoming           14
Name: count, dtype: int64

### Penggunaan func groupby()

Fungsi yang sangat kuat untuk mengelompokkan data berdasarkan satu atau lebih kolom, lalu menerapkan fungsi statistik pada kelompok tersebut.

In [20]:
# menerapkan func groupby pada df coffee
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [22]:
# ingin mengetahui jumlah penjualan dari tipe kopi yang dijual 

coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    246.666667
Latte       203.333333
Name: Units Sold, dtype: float64

In [23]:
# ingin mengetahui rata - rata penjualan dari tipe kopi yang dijual 
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    35.238095
Latte       29.047619
Name: Units Sold, dtype: float64

### menggunaka func .agg()

Memungkinkan Anda menjalankan berbagai fungsi perhitungan berbeda pada kolom yang berbeda sekaligus menggunakan kamus (dictionary). Contoh: menghitung total (sum) pada kolom penjualan dan rata-rata (mean) pada kolom harga secara bersamaan.

In [25]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price': 'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday      45.000000   3.99
            Monday      15.000000   3.99
            Saturday    45.000000   3.99
            Sunday      45.000000   3.99
            Thursday    40.000000   3.99
            Tuesday     21.666667   3.99
            Wednesday   35.000000   3.99
Latte       Friday      35.000000   5.99
            Monday      15.000000   5.99
            Saturday    35.000000   5.99
            Sunday      35.000000   5.99
            Thursday    30.000000   5.99
            Tuesday     28.333333   5.99
            Wednesday   25.000000   5.99

### Membuat sebuah Pivot dengan func pivot atau pivot_table

In [26]:
pivot = coffee.pivot_table(columns='Coffee Type', index='Day', values='revenue')

In [27]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [28]:
# lets say kita ingin menjumlahkan sebuah pendapatan nya 
pivot.sum()

Coffee Type
Espresso    1057.35
Latte       1168.05
dtype: float64

In [30]:
# melihat total pendapatan kedua jenis kopi di hari yang sama dengan parameter axis
pivot.sum(axis=1)

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

### sekarang belajar dengan dataframe informasi atlet

In [31]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [32]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [43]:
# kita mengubah tipe kolom born_date menjadi sebuah tipe datetime
bios['born_date'] = pd.to_datetime(bios['born_date'], errors='coerce')

In [44]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  datetime64[ns]
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
 10  born_year     143693 non-null  float64
 11  born_month    143693 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(6)
memory usage: 13.3+ MB

In [45]:
# mengetahui jumlah orang dengan tahun lahir yang sama

# memakai func reset_index() agar menjadi table
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index()

     born_date  name
0       1828.0     1
1       1831.0     2
2       1833.0     1
3       1836.0     1
4       1837.0     1
..         ...   ...
172     2005.0   163
173     2006.0    17
174     2007.0     3
175     2008.0     3
176     2009.0     1

[177 rows x 2 columns]

In [ ]:
# mengetahui jumlah orang dengan tahun lahir dan bulan yang sama
bios['born_year'] = bios['born_date'].dt.year
bios['born_month'] = bios['born_date'].dt.month

bios.groupby([bios['born_year'], bios['born_month']])['name'].count().reset_index().sort_values('name', ascending=False)

      born_year  born_month  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1629     1986.0         1.0   227
1497     1975.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
95       1857.0         5.0     1
96       1857.0         7.0     1
97       1857.0         8.0     1
98       1857.0         9.0     1
1884     2009.0         1.0     1

[1885 rows x 3 columns]