# Aggregating Data

proses menggabungkan, mengelompokkan, atau meringkas banyak baris data menjadi satu nilai ringkasan yang bermakna. Tujuan utamanya adalah untuk melihat pola besar dari dataset, bukan hanya melihat baris data satu per satu.

In [15]:
# import library 

import pandas as pd
import numpy as np

In [16]:
# Load dataframe

# Dataframe Bios
bios = pd.read_csv('data/bios.csv')

# Dataframe coffe
coffee = pd.read_csv('data/coffee_update.csv')

In [17]:
# melihat jumlah orang yang lahir di tempat yang sama berdasarkan kolom 'born_city'

bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Bodrogkisfalud        1
Ternberg              1
Klaus                 1
Plaški                1
Dulwich Hill          1
Name: count, Length: 22368, dtype: int64

In [18]:
# melihat info jumlah orang yang berada di amerika berdasarkan region yang sama
bios[bios['born_country'] == "USA"]['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
South Carolina            50
Maine                     50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [19]:
# melihat info jumlah orang yang berada di amerika berdasarkan region yang sama dari urutan belakang atau terkecil 

bios[bios['born_country'] == "USA"]['born_region'].value_counts().tail(25)

born_region
Utah              91
Missouri          91
North Carolina    86
Arizona           83
New Hampshire     83
Vermont           68
Mississippi       66
Alabama           64
Kentucky          62
Tennessee         62
Nebraska          60
Rhode Island      56
Montana           55
South Carolina    50
Maine             50
Alaska            45
Arkansas          42
Idaho             41
New Mexico        38
Nevada            36
South Dakota      27
West Virginia     24
Delaware          22
North Dakota      16
Wyoming           14
Name: count, dtype: int64

### Penggunaan func groupby()

Fungsi yang sangat kuat untuk mengelompokkan data berdasarkan satu atau lebih kolom, lalu menerapkan fungsi statistik pada kelompok tersebut.

In [20]:
# menerapkan func groupby pada df coffee
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [22]:
# ingin mengetahui jumlah penjualan dari tipe kopi yang dijual 

coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    246.666667
Latte       203.333333
Name: Units Sold, dtype: float64

In [23]:
# ingin mengetahui rata - rata penjualan dari tipe kopi yang dijual 
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    35.238095
Latte       29.047619
Name: Units Sold, dtype: float64

### menggunaka func .agg()

Memungkinkan Anda menjalankan berbagai fungsi perhitungan berbeda pada kolom yang berbeda sekaligus menggunakan kamus (dictionary). Contoh: menghitung total (sum) pada kolom penjualan dan rata-rata (mean) pada kolom harga secara bersamaan.

In [25]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price': 'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday      45.000000   3.99
            Monday      15.000000   3.99
            Saturday    45.000000   3.99
            Sunday      45.000000   3.99
            Thursday    40.000000   3.99
            Tuesday     21.666667   3.99
            Wednesday   35.000000   3.99
Latte       Friday      35.000000   5.99
            Monday      15.000000   5.99
            Saturday    35.000000   5.99
            Sunday      35.000000   5.99
            Thursday    30.000000   5.99
            Tuesday     28.333333   5.99
            Wednesday   25.000000   5.99

### Membuat sebuah Pivot dengan func pivot atau pivot_table

In [26]:
pivot = coffee.pivot_table(columns='Coffee Type', index='Day', values='revenue')

In [27]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [28]:
# lets say kita ingin menjumlahkan sebuah pendapatan nya 
pivot.sum()

Coffee Type
Espresso    1057.35
Latte       1168.05
dtype: float64

In [30]:
# melihat total pendapatan kedua jenis kopi di hari yang sama dengan parameter axis
pivot.sum(axis=1)

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

### sekarang belajar dengan dataframe informasi atlet

In [31]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [32]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [43]:
# kita mengubah tipe kolom born_date menjadi sebuah tipe datetime
bios['born_date'] = pd.to_datetime(bios['born_date'], errors='coerce')

In [44]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  datetime64[ns]
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
 10  born_year     143693 non-null  float64
 11  born_month    143693 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(6)
memory usage: 13.3+ MB

In [45]:
# mengetahui jumlah orang dengan tahun lahir yang sama

# memakai func reset_index() agar menjadi table
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index()

     born_date  name
0       1828.0     1
1       1831.0     2
2       1833.0     1
3       1836.0     1
4       1837.0     1
..         ...   ...
172     2005.0   163
173     2006.0    17
174     2007.0     3
175     2008.0     3
176     2009.0     1

[177 rows x 2 columns]

In [ ]:
# mengetahui jumlah orang dengan tahun lahir dan bulan yang sama
bios['born_year'] = bios['born_date'].dt.year
bios['born_month'] = bios['born_date'].dt.month

bios.groupby([bios['born_year'], bios['born_month']])['name'].count().reset_index().sort_values('name', ascending=False)

      born_year  born_month  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1629     1986.0         1.0   227
1497     1975.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
95       1857.0         5.0     1
96       1857.0         7.0     1
97       1857.0         8.0     1
98       1857.0         9.0     1
1884     2009.0         1.0     1

[1885 rows x 3 columns]

## Praktek

In [47]:
# load dataframe baru 

df_car = pd.read_csv('data/car_sales.csv')

In [63]:
df_car.head()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

In [64]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         157 non-null    object
 1   Model                157 non-null    object
 2   Sales_in_thousands   157 non-null    float64
 3   __year_resale_value  121 non-null    float64
 4   Vehicle_type         157 non-null    object
 5   Price_in_thousands   155 non-null    float64
 6   Engine_size          156 non-null    float64
 7   Horsepower           156 non-null    float64
 8   Wheelbase            156 non-null    float64
 9   Width                156 non-null    float64
 10  Length               156 non-null    float64
 11  Curb_weight          155 non-null    float64
 12  Fuel_capacity        156 non-null    float64
 13  Fuel_efficiency      154 non-null    float64
 14  Latest_Launch        157 non-null    object
 15  Power_perf_factor    155 non-null    float64
dtypes: float64(12), object(4)
memory usage: 19.8+ KB

In [66]:
df_car

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [65]:
# menampilkan sebuah brand dengan model terbanyak
df_car['Manufacturer'].value_counts().reset_index().head(10)

  Manufacturer  count
0        Dodge     11
1         Ford     11
2       Toyota      9
3    Chevrolet      9
4   Mercedes-B      9
5   Mitsubishi      7
6       Nissan      7
7     Chrysler      7
8        Volvo      6
9   Oldsmobile      6

In [ ]:
# Kelompokkan data berdasarkan Vehicle_type dan hitung(mean) dari Horsepower, Price_in_thousands, dan Fuel_efficiency untuk masing-masing tipe tersebut.

df_car.groupby(['Vehicle_type']).agg({'Horsepower':'mean', 'Price_in_thousands':'mean', 'Fuel_efficiency':'mean'})

              Horsepower  Price_in_thousands  Fuel_efficiency
Vehicle_type
Car           186.400000           26.319975        19.700000
Passenger     185.793103           27.763200        25.298246

Analisis Penjualan per Manufaktur (Level: Advanced)
Ini bagian paling krusial. Saya butuh tabel performa untuk setiap brand.

Tugas: Gunakan .groupby() pada kolom Manufacturer lalu gunakan fungsi .agg() untuk menghitung:

- Total penjualan (Sales_in_thousands) menggunakan sum.

- Harga tertinggi (Price_in_thousands) menggunakan max.

- Rata-rata efisiensi bahan bakar (Fuel_efficiency) menggunakan mean.

Goal: Urutkan hasilnya berdasarkan Total Penjualan terbanyak (descending).

In [87]:
laporan_analisis = df_car.groupby('Manufacturer').agg({
    'Sales_in_thousands': 'sum',
    'Price_in_thousands': 'max',
    'Fuel_efficiency': 'mean'
    }).reset_index().sort_values(by='Sales_in_thousands', ascending=False)

In [88]:
laporan_analisis

   Manufacturer  Sales_in_thousands  Price_in_thousands  Fuel_efficiency
8          Ford            2022.635              36.135        22.818182
7         Dodge             910.149              69.725        20.100000
27       Toyota             740.205              51.728        25.222222
9         Honda             592.674              26.600        25.000000
5     Chevrolet             554.365              45.705        28.444444
19       Nissan             399.635              29.299        22.285714
22      Pontiac             370.534              25.635        24.833333
13         Jeep             293.153              26.895        18.666667
3         Buick             242.019              31.965        24.250000
17      Mercury             237.999              27.560        23.666667
28   Volkswagen             209.212              21.200        26.166667
6      Chrysler             201.721              29.185        24.500000
18   Mitsubishi             180.895              31.807        22.857143
20   Oldsmobile             178.989              36.229        23.000000
25       Saturn             168.850              18.835        30.400000
10      Hyundai             137.326              14.999        27.666667
16   Mercedes-B             117.125              85.500        23.444444
4      Cadillac             112.178              46.225        20.600000
14        Lexus             106.843              60.105        20.833333
15      Lincoln              85.634              43.330        19.333333
26       Subaru              80.135              22.695        24.500000
0         Acura              79.005              42.000        25.250000
29        Volvo              75.740              45.500        24.500000
21     Plymouth              64.001              43.000        25.250000
2           BMW              46.505              38.900        25.000000
1          Audi              40.557              62.000        23.333333
11     Infiniti              23.713              29.465        25.000000
24         Saab              21.306              33.120        23.000000
12       Jaguar              15.467              42.800        21.000000
23      Porsche              12.128              74.970        22.000000

Saya ingin melihat brand mana yang paling seimbang antara tenaga dan keiritan.

Tugas: Kelompokkan berdasarkan Manufacturer, lalu hitung rata-rata Horsepower dan Fuel_efficiency.

Filter: Hanya tampilkan brand yang memiliki rata-rata Horsepower di atas 200.

In [ ]:
comparison_brand = df_car.groupby(['Manufacturer']).agg({
    'Horsepower' : 'mean',
    'Fuel_efficiency' : 'mean'
    }).reset_index().query('Horsepower > 200').sort_values(by='Horsepower', ascending=False)

In [102]:
comparison_brand

   Manufacturer  Horsepower  Fuel_efficiency
23      Porsche  272.333333        22.000000
15      Lincoln  263.333333        19.333333
4      Cadillac  256.000000        20.600000
14        Lexus  245.833333        20.833333
12       Jaguar  240.000000        21.000000
16   Mercedes-B  232.222222        23.444444
11     Infiniti  227.000000        25.000000
1          Audi  220.000000        23.333333
3         Buick  206.250000        24.250000

Tugas 1: Agregasi Bertingkat (Agg)
Gunakan method chaining untuk:

1. Mengelompokkan data berdasarkan Manufacturer.

2. Hitung total Sales_in_thousands dan rata-rata Price_in_thousands secara bersamaan.

3. Urutkan hasilnya berdasarkan total penjualan dari yang tertinggi ke terendah.

Gunakan .reset_index() agar hasilnya menjadi DataFrame yang rapi.

In [110]:
df_car.groupby(['Manufacturer']).agg({
    'Sales_in_thousands' : 'sum',
    'Price_in_thousands' : 'mean'
}).reset_index().sort_values(by='Sales_in_thousands', ascending=False)

   Manufacturer  Sales_in_thousands  Price_in_thousands
8          Ford            2022.635           21.047273
7         Dodge             910.149           24.213636
27       Toyota             740.205           21.982889
9         Honda             592.674           20.277000
5     Chevrolet             554.365           20.022778
19       Nissan             399.635           22.360714
22      Pontiac             370.534           22.949167
13         Jeep             293.153           20.991667
3         Buick             242.019           26.781250
17      Mercury             237.999           20.748333
28   Volkswagen             209.212           17.698333
6      Chrysler             201.721           23.430833
18   Mitsubishi             180.895           22.167429
20   Oldsmobile             178.989           25.622833
25       Saturn             168.850           14.271000
10      Hyundai             137.326           12.165667
16   Mercedes-B             117.125           52.916667
4      Cadillac             112.178           40.254000
14        Lexus             106.843           44.055000
15      Lincoln              85.634           41.690000
26       Subaru              80.135           21.395000
0         Acura              79.005           30.633333
29        Volvo              75.740           30.933333
21     Plymouth              64.001           22.642500
2           BMW              46.505           33.096667
1          Audi              40.557           39.980000
11     Infiniti              23.713           29.465000
24         Saab              21.306           29.610000
12       Jaguar              15.467           42.800000
23      Porsche              12.128           62.473333

Tugas 2: Pivot Table Multi-Dimensi
Buatlah sebuah Pivot Table yang:

1. Menjadikan Year sebagai index (baris).

2. Menjadikan Vehicle_type sebagai columns (horizontal).

3. Menghitung rata-rata dari Sales_in_thousands sebagai values-nya.

Tambahkan parameter fill_value=0 untuk menangani data yang kosong.

In [111]:
df_car['Latest_Launch'] = pd.to_datetime(df_car['Latest_Launch'])

In [107]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         157 non-null    object
 1   Model                157 non-null    object
 2   Sales_in_thousands   157 non-null    float64
 3   __year_resale_value  121 non-null    float64
 4   Vehicle_type         157 non-null    object
 5   Price_in_thousands   155 non-null    float64
 6   Engine_size          156 non-null    float64
 7   Horsepower           156 non-null    float64
 8   Wheelbase            156 non-null    float64
 9   Width                156 non-null    float64
 10  Length               156 non-null    float64
 11  Curb_weight          155 non-null    float64
 12  Fuel_capacity        156 non-null    float64
 13  Fuel_efficiency      154 non-null    float64
 14  Latest_Launch        157 non-null    datetime64[ns]
 15  Power_perf_factor    155 non-null    float64
dtypes: datetime64[ns](1), float64(12), object(3)
memory usage: 19.8+ KB

In [108]:
df_car['year'] = df_car['Latest_Launch'].dt.year

In [122]:
pivot = df_car.pivot_table(columns='Vehicle_type', index='year', values='Sales_in_thousands',aggfunc='mean', fill_value=0)
pivot

Vehicle_type        Car  Passenger
year
2008          27.609000   0.000000
2009          20.380000  80.255000
2011          61.098437  43.489365
2012          99.128261  42.213442

Tugas 3: Analisis Spesifik (Value Counts)
Tampilkan 5 produsen mobil (Manufacturer) teratas yang paling sering muncul dalam dataset ini.

In [125]:
df_car['Manufacturer'].value_counts().reset_index().head(5)

  Manufacturer  count
0        Dodge     11
1         Ford     11
2       Toyota      9
3    Chevrolet      9
4   Mercedes-B      9