# Handling null values

In [87]:
# import library 

import pandas as pd
import numpy as np

In [88]:
# load dataframe

coffe = pd.read_csv('data/coffee.csv')

In [89]:
coffe.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [90]:
# buat kolom price dimana Espresso = 3.99 dan Latte = 5.99

coffe['price'] = np.where(coffe['Coffee Type'] == "Espresso", 3.99, 5.99)

In [91]:
coffe.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   3.99
1     Monday       Latte          15   5.99
2    Tuesday    Espresso          30   3.99
3    Tuesday       Latte          20   5.99
4  Wednesday    Espresso          35   3.99

In [92]:
# buat kolom revenue
coffe['revenue'] = coffe['Units Sold'] * coffe['price']

In [93]:
coffe.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [94]:
# membuat data indexs baris 0 dan 1 menjadi NaN

coffe.loc[[0,1], 'Units Sold'] = np.nan

In [95]:
coffe.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso         NaN   3.99    99.75
1     Monday       Latte         NaN   5.99    89.85
2    Tuesday    Espresso        30.0   3.99   119.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65

In [96]:
# cara cek data memiliki suati nilai atau bernilai NaN
coffe.info()


# di Units Sold terdapat 12 non-null dimana berarti ada 2 null di kolom tersebut

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   12 non-null     float64
 3   price        14 non-null     float64
 4   revenue      14 non-null     float64
dtypes: float64(3), object(2)
memory usage: 692.0+ bytes

In [97]:
# opsi lain mencari data NaN
coffe.isna().sum()

# terdapat 2 data null di kolom Units Sold

Day            0
Coffee Type    0
Units Sold     2
price          0
revenue        0
dtype: int64

In [98]:
# mengisi data null dengan mean kolom 'Units Sold' dengan fungsi .fillna()

# coffe.fillna(coffe['Units Sold'].mean())

In [99]:
coffe.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso         NaN   3.99    99.75
1     Monday       Latte         NaN   5.99    89.85
2    Tuesday    Espresso        30.0   3.99   119.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65

In [100]:
# mengosongkan data dengan NaN di indexs baris 2 dan 3
coffe.loc[[2,3], 'Units Sold'] = np.nan

In [101]:
coffe

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso         NaN   3.99    99.75
1      Monday       Latte         NaN   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [102]:
coffe.loc[[0,1],'Units Sold'] = 15

In [103]:
coffe

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

### kita bisa mengisi data null dengan sebuah fungsi interpolate dimana digunakan untuk mengisi nilai yang hilang (NaN) dengan cara memperkirakan nilai tersebut berdasarkan titik data lain yang ada di sekitarnya.

berusaha menjaga tren atau pola yang ada dalam kolom tersebut.

syntax :

coffe['Units Sold'] = coffe['Units Sold'].interpolate()

In [104]:
coffe

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [105]:
# menghapus sebuah data dengan nilai null dengan fungsi .dropna()

# dalam fungsi dropna terdapat sebuah parameter subset dimana ini digunakan jika kolom yang ditandai dalam subset berisi NaN maka hapus barisnya

# coffe = coffe.dropna(subset=['Units Sold'])

In [106]:
# coffe

In [107]:
# cara lain menampilkan mana data yang NaN dan tidak NaN


# menampilkan data yang NaN
coffe[coffe['Units Sold'].isna()]

       Day Coffee Type  Units Sold  price  revenue
2  Tuesday    Espresso         NaN   3.99    119.7
3  Tuesday       Latte         NaN   5.99    119.8

In [108]:
# menampilkan data yang tidak NaN
coffe[coffe['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65