# Handling null values

In [160]:
# import library 

import pandas as pd
import numpy as np

In [161]:
# load dataframe

coffe = pd.read_csv('data/coffee.csv')

In [162]:
coffe.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [163]:
# buat kolom price dimana Espresso = 3.99 dan Latte = 5.99

coffe['price'] = np.where(coffe['Coffee Type'] == "Espresso", 3.99, 5.99)

In [164]:
coffe.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   3.99
1     Monday       Latte          15   5.99
2    Tuesday    Espresso          30   3.99
3    Tuesday       Latte          20   5.99
4  Wednesday    Espresso          35   3.99

In [165]:
# buat kolom revenue
coffe['revenue'] = coffe['Units Sold'] * coffe['price']

In [166]:
coffe.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [167]:
# membuat data indexs baris 0 dan 1 menjadi NaN

coffe.loc[[0,1], 'Units Sold'] = np.nan

In [168]:
coffe.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso         NaN   3.99    99.75
1     Monday       Latte         NaN   5.99    89.85
2    Tuesday    Espresso        30.0   3.99   119.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65

In [169]:
# cara cek data memiliki suati nilai atau bernilai NaN
coffe.info()


# di Units Sold terdapat 12 non-null dimana berarti ada 2 null di kolom tersebut

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   12 non-null     float64
 3   price        14 non-null     float64
 4   revenue      14 non-null     float64
dtypes: float64(3), object(2)
memory usage: 692.0+ bytes

In [170]:
# opsi lain mencari data NaN
coffe.isna().sum()

# terdapat 2 data null di kolom Units Sold

Day            0
Coffee Type    0
Units Sold     2
price          0
revenue        0
dtype: int64

In [171]:
# mengisi data null dengan mean kolom 'Units Sold' dengan fungsi .fillna()

# coffe.fillna(coffe['Units Sold'].mean())

In [172]:
coffe.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso         NaN   3.99    99.75
1     Monday       Latte         NaN   5.99    89.85
2    Tuesday    Espresso        30.0   3.99   119.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65

In [173]:
# mengosongkan data dengan NaN di indexs baris 2 dan 3
coffe.loc[[2,3], 'Units Sold'] = np.nan

In [174]:
coffe

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso         NaN   3.99    99.75
1      Monday       Latte         NaN   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [175]:
coffe.loc[[0,1],'Units Sold'] = 15

In [176]:
coffe

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

### kita bisa mengisi data null dengan sebuah fungsi interpolate dimana digunakan untuk mengisi nilai yang hilang (NaN) dengan cara memperkirakan nilai tersebut berdasarkan titik data lain yang ada di sekitarnya.

berusaha menjaga tren atau pola yang ada dalam kolom tersebut.

syntax :

coffe['Units Sold'] = coffe['Units Sold'].interpolate()

In [177]:
coffe

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [178]:
# menghapus sebuah data dengan nilai null dengan fungsi .dropna()

# dalam fungsi dropna terdapat sebuah parameter subset dimana ini digunakan jika kolom yang ditandai dalam subset berisi NaN maka hapus barisnya

# coffe = coffe.dropna(subset=['Units Sold'])

In [179]:
# coffe

In [180]:
# cara lain menampilkan mana data yang NaN dan tidak NaN


# menampilkan data yang NaN
coffe[coffe['Units Sold'].isna()]

       Day Coffee Type  Units Sold  price  revenue
2  Tuesday    Espresso         NaN   3.99    119.7
3  Tuesday       Latte         NaN   5.99    119.8

In [181]:
# menampilkan data yang tidak NaN
coffe[coffe['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

# Praktek

In [182]:
# load dataframe
df_coffee = pd.read_csv('data/coffee_sales.csv')

In [183]:
df_coffee.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [184]:
df_coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   object
 1   datetime     3636 non-null   object
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

In [185]:
# menampilkan ringkasan jumlah NaN di setiap Kolom

df_coffee.isna().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [186]:
# menampilkan data dengan nilai kolom card NaN
df_coffee[df_coffee['card'].isna()]

,date,datetime,cash_type,card,money,coffee_name
12,2024-03-02,2024-03-02 10:30:35.668,cash,NaN,40.0,Latte
18,2024-03-03,2024-03-03 10:10:43.981,cash,NaN,40.0,Latte
41,2024-03-06,2024-03-06 12:30:27.089,cash,NaN,35.0,Americano with Milk
46,2024-03-07,2024-03-07 10:08:58.945,cash,NaN,40.0,Latte
49,2024-03-07,2024-03-07 11:25:43.977,cash,NaN,40.0,Latte
...,...,...,...,...,...,...
657,2024-05-31,2024-05-31 09:23:58.791,cash,NaN,39.0,Latte
677,2024-06-01,2024-06-01 20:54:59.267,cash,NaN,39.0,Cocoa
685,2024-06-02,2024-06-02 22:43:10.636,cash,NaN,34.0,Americano with Milk
691,2024-06-03,2024-06-03 21:42:51.734,cash,NaN,34.0,Americano with Milk
692,2024-06-03,2024-06-03 21:43:37.471,cash,NaN,34.0,Americano with Milk

In [187]:
# mengosongkan nilai di index 10 - 20 di kolom money
df_coffee.loc[10:20, 'money'] = np.nan

# mengosongkan nilai di index 50-55 di kolom coffee_name
df_coffee.loc[50:55, 'coffee_name'] = np.nan

In [188]:
df_coffee.isna().sum()

date            0
datetime        0
cash_type       0
card           89
money          11
coffee_name     6
dtype: int64

In [ ]:
# mengganti nilai NaN di kolom card dengan "CASH_PAYMENT"
df_coffee['card'] = df_coffee['card'].fillna("CASH_PAYMENT")

In [191]:
df_coffee[df_coffee['card'] == "CASH_PAYMENT"]

,date,datetime,cash_type,card,money,coffee_name
12,2024-03-02,2024-03-02 10:30:35.668,cash,CASH_PAYMENT,NaN,Latte
18,2024-03-03,2024-03-03 10:10:43.981,cash,CASH_PAYMENT,NaN,Latte
41,2024-03-06,2024-03-06 12:30:27.089,cash,CASH_PAYMENT,35.0,Americano with Milk
46,2024-03-07,2024-03-07 10:08:58.945,cash,CASH_PAYMENT,40.0,Latte
49,2024-03-07,2024-03-07 11:25:43.977,cash,CASH_PAYMENT,40.0,Latte
...,...,...,...,...,...,...
657,2024-05-31,2024-05-31 09:23:58.791,cash,CASH_PAYMENT,39.0,Latte
677,2024-06-01,2024-06-01 20:54:59.267,cash,CASH_PAYMENT,39.0,Cocoa
685,2024-06-02,2024-06-02 22:43:10.636,cash,CASH_PAYMENT,34.0,Americano with Milk
691,2024-06-03,2024-06-03 21:42:51.734,cash,CASH_PAYMENT,34.0,Americano with Milk
692,2024-06-03,2024-06-03 21:43:37.471,cash,CASH_PAYMENT,34.0,Americano with Milk

In [192]:
# untuk kolom coffee_name, Jika nama kopinya hilang, data itu harus dibuang karena kita tidak tahu stok apa yang berkurang.
df_coffee.dropna(subset='coffee_name',inplace=True)

In [194]:
df_coffee.isna().sum()

date            0
datetime        0
cash_type       0
card            0
money          11
coffee_name     0
dtype: int64

In [195]:
df_coffee['money'] = df_coffee['money'].interpolate()

In [196]:
df_coffee

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [197]:
# mengecek ulang nilai NaN final
df_coffee.isna().sum()

date           0
datetime       0
cash_type      0
card           0
money          0
coffee_name    0
dtype: int64

In [ ]:
# save data coffee_sales bersih tanpa NaN