# Pandas

sebuah pustaka (library) dalam bahasa pemrograman Python yang secara khusus digunakan untuk bekerja dengan, menganalisis, dan memanipulasi data tabular atau data berbentuk spreadsheet.

In [1]:
import pandas as pd

In [2]:
# membuat sebuah DataFrame sederhana

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], columns=["A","B","C"], index=["row1","row2","row3","row4"])

In [3]:
# dalam fungsi head(berapa baris yang ingin ditampilkan) dia menampilkan sebuah data frame dari atas/awal
df.head()

       A   B   C
row1   1   2   3
row2   4   5   6
row3   7   8   9
row4  10  11  12

In [4]:
# dalam fungsi tail(berapa baris yang ingin ditampilkan) dia menampilkan baris dimulai dari akhir
df.tail(2)

       A   B   C
row3   7   8   9
row4  10  11  12

In [5]:
df

       A   B   C
row1   1   2   3
row2   4   5   6
row3   7   8   9
row4  10  11  12

In [6]:
# untuk mengetahui atau mengakses column dan jenis nya
df.columns

Index(['A', 'B', 'C'], dtype='object')

untuk mengubah sebuah default index di data frame yang tadinya 0,1,2 menjadi sesuka kita kita bisa menambahkan sebuah index pada parameter index dengan apapun yang kita mau, disini kita mengubah nya dengan nama row1,row2,row3.

In [7]:
df.shape

(4, 3)

disini kita tahu ukuran data frame kita yaitu 2 dimensi dengan 3 baris dan 3 kolom

### Describe()

untuk menampilkan ringkasan informasi statistik dari data yang ada di dalam Data Frame Anda

In [8]:
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [9]:
# untuk mengetahui informasi tentang data frame yang kita buat
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes

### unique()

Berfungsi untuk menemukan dan menampilkan nilai-nilai unik (spesifik) apa saja yang ada di dalam sebuah kolom

In [10]:
df["B"].unique()

array([ 2,  5,  8, 11])

### nunique()

Berfungsi untuk menghitung berapa banyak jumlah nilai unik yang terdapat di dalam kolom tersebut.

In [11]:
df.nunique()

A    4
B    4
C    4
dtype: int64

In [12]:
df.index.to_list()

['row1', 'row2', 'row3', 'row4']

# Praktek

In [1]:
# challenge 1

# mengimport pandas
import pandas as pd

# membua sebuah data dictionary
aktivitas_trade = {
    "Hari": ["Senin", "Selasa", "Rabu", "Kamis", "Jumat"],
    "Cangkir_kopi" : [2,3,1,5,2],
    "Profit_USD" : [50,-20,100,45,-10]
}

# mengubah sebuah dictionary menjadi dataframe
df_haerul = pd.DataFrame(aktivitas_trade)

# menampilkan dataframe
df_haerul

     Hari  Cangkir_kopi  Profit_USD
0   Senin             2          50
1  Selasa             3         -20
2    Rabu             1         100
3   Kamis             5          45
4   Jumat             2         -10

In [2]:
# menampilkan 3 data pertama
df_haerul.head(3)

     Hari  Cangkir_kopi  Profit_USD
0   Senin             2          50
1  Selasa             3         -20
2    Rabu             1         100

In [3]:
# mengetahui info dataframe
df_haerul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Hari          5 non-null      object
 1   Cangkir_kopi  5 non-null      int64
 2   Profit_USD    5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [4]:
# menampilkan statistik deskriptif
df_haerul.describe()

       Cangkir_kopi  Profit_USD
count      5.000000    5.000000
mean       2.600000   33.000000
std        1.516575   48.938737
min        1.000000  -20.000000
25%        2.000000  -10.000000
50%        2.000000   45.000000
75%        3.000000   50.000000
max        5.000000  100.000000

In [5]:
# menampilkan dimensi tabel 
df_haerul.shape

(5, 3)