# Memuat sebuah DataFrame dari File CSV

In [3]:
import pandas as pd

In [4]:
coffe = pd.read_csv('data/coffee.csv') # memuat sebuah dataframe dari file csv

In [5]:
coffe.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

## memuat sebuah dataframe dari file selain csv

In [6]:
# memuat sebuah DataFrame dari file parquet
result_parquet = pd.read_parquet('data/results.parquet')

In [7]:
result_parquet.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [8]:
result_parquet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

In [9]:
# memuat file feather 
result_feather = pd.read_feather('data/results.feather')
result_feather.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [10]:
# memuat file xlsx
result_xlsx = pd.read_excel('data/olympics-data.xlsx', sheet_name='results') # mengakses sebuah file excel khusus nya di sheet results

In [11]:
result_xlsx.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [12]:
# parquet cocok untuk speed read
# csv cocok untuk biasanya universal
# excel cocok untuk multisheet

# Praktek

In [17]:
# challenge 1
# membua sebuah data dictionary
aktivitas_trade = {
    "Hari": ["Senin", "Selasa", "Rabu", "Kamis", "Jumat"],
    "Cangkir_kopi" : [2,3,1,5,2],
    "Profit_USD" : [50,-20,100,45,-10]
}

# mengubah sebuah dictionary menjadi dataframe
df_haerul = pd.DataFrame(aktivitas_trade)

df_haerul.to_csv("data/df_haerul.csv", index=False)

In [18]:
df_haerul

     Hari  Cangkir_kopi  Profit_USD
0   Senin             2          50
1  Selasa             3         -20
2    Rabu             1         100
3   Kamis             5          45
4   Jumat             2         -10

In [19]:
del aktivitas_trade # menghapus sebuah variabel aktivitas_trade

In [20]:
# memuat data format csv
aktivitas_trade = pd.read_csv("data/df_haerul.csv")

# menampilkan 3 data pertama
aktivitas_trade.head(3)

     Hari  Cangkir_kopi  Profit_USD
0   Senin             2          50
1  Selasa             3         -20
2    Rabu             1         100

In [21]:
# Membuat file dengan pemisah Tab
with open('data_rahasia.txt', 'w') as f:
    f.write("Aset\tSignal\tPrice\nBTC\tBUY\t65000\nETH\tSELL\t3500\nSOL\tHOLD\t140")

In [22]:
data_rahasia = pd.read_csv("data_rahasia.txt", sep="\t")

In [23]:
data_rahasia

  Aset Signal  Price
0  BTC    BUY  65000
1  ETH   SELL   3500
2  SOL   HOLD    140