# Merging & Concetenating Data

In [1]:
# Import Library

import pandas as pd

In [13]:
# Load Dataset bios

bios = pd.read_csv('data/bios.csv')

In [14]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [15]:
# Load Dataset ke-2 
nocs = pd.read_csv('data/noc_regions.csv')
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [16]:
# merge Dataframe 
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

In [17]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [18]:
# rename kolom 'region' dengan 'born_country_full

bios_new.rename(columns={'region':'born_country_full'}, inplace=True)

In [19]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

di dalam sebuah dataframe baru 'bios_new' hasil dari merging terdapat kolom yang bernama NOC_x dan NOC_y, ini terjadi karena di dalam kedua Dataframe ini terdapat Kolom yang Sama namun dengan isi yang berbeda.

In [ ]:
# kita ingin mengubah sebuah nama kolom NOC_x dan NOC_y dengan sufixes

# bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left', suffixes=["bios","nocdf"])

In [20]:
# melihat sebuah data dimana NOC_x tidak sama dengan Born Country Full
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name','NOC_x','born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [22]:
# contoh concatenate

# hanya mengambil bio athlete dari USA saja
USA = bios[bios['born_country'] == "USA"].copy()

# hanya mengambil bio athlete dari gbr saja
GBR = bios[bios['born_country'] == "GBR"].copy()

In [23]:
USA.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN

In [24]:
USA.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [25]:
GBR.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26
38,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10
39,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN

In [26]:
GBR.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN

In [27]:
new_df = pd.concat([USA,GBR])       # menyambungkan Dataframe by defaul kiri = atas, kanan = bawah)

In [28]:
new_df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN

In [30]:
# load Dataframe result 
result = pd.read_parquet('data/results.parquet')

In [31]:
result.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [38]:
# merge df result,bios dimana jangkar nya yaitu athlete_id

# kita ingin mengetahui info hasil dari suatu athlete baik penting atau tidak nya pertandingan itu.
combined_df = pd.merge(result,bios, on='athlete_id', how='left')

In [39]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

# Praktek

In [40]:
# challenge 1

# membuat sebuah dataframe baru dimana hanya athlete indonesia saja 

INA = bios[bios['born_country'] == "INA"].copy()

# membuat sebuah dataframe baru dimana hanya athlete malaysia saja 

MAS = bios[bios['born_country'] == "MAS"].copy()

In [41]:
INA.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
232,233,Yayuk Basuki,1970-11-30,Yogyakarta,Daerah Istimewa Yogyakarta,INA,Indonesia,165.0,55.0,NaN
233,234,Rossy Pratiwi Dipoyanti,1972-06-28,Bandung,Jawa Barat,INA,Indonesia,NaN,NaN,NaN
234,235,Finarsih,1972-02-08,Sleman,Jawa Tengah,INA,Indonesia,NaN,NaN,NaN
235,236,Ling Ling Agustin,1969-08-23,Kediri,Jawa Timur,INA,Indonesia,NaN,NaN,NaN
238,239,Zelin Resiana,1972-07-09,Magelang,Jawa Tengah,INA,Indonesia,169.0,58.0,NaN

In [42]:
INA.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
140211,143712,Jonatan Christie,1997-09-15,Jakarta,Daerah Khusus Ibukota Jakarta,INA,Indonesia,NaN,NaN,NaN
140212,143713,Kevin Sanjaya Sukamuljo,1995-08-02,Banyuwangi,Jawa Timur,INA,Indonesia,NaN,NaN,NaN
140213,143714,Marcus Fernaldi Gideon,1991-03-09,Jakarta,Daerah Khusus Ibukota Jakarta,INA,Indonesia,NaN,NaN,NaN
140215,143716,Aflah Prawira,1997-11-13,Cirebon,Jawa Barat,INA,Indonesia,NaN,NaN,NaN
140216,143717,Rahmat Abdullah,2000-10-13,Makassar,Sulawesi Selatan,INA,Indonesia,NaN,NaN,NaN

In [43]:
MAS.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
950,954,Cheah Soon Kit,1968-01-09,Ipoh,Perak,MAS,Malaysia,180.0,73.0,NaN
952,956,Ong Ewe Hock,1972-03-14,Penang,Pulau Pinang,MAS,Malaysia,163.0,55.0,NaN
953,957,Alan Sidek Mohamed,1963-11-10,Banting,Selangor,MAS,Malaysia,178.0,69.0,NaN
954,958,Ajib Sidek Mohamed,1968-07-08,Banting,Selangor,MAS,Malaysia,180.0,68.0,NaN
958,962,Yap Kim Hock,1970-07-02,Muar,Johor,MAS,Malaysia,160.0,60.0,NaN

In [44]:
MAS.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
132242,135093,Welson Sim,1997-03-29,Kuching,Sarawak,MAS,Malaysia,181.0,70.0,NaN
132243,135094,Mohammad Hafifi bin Mansor,1990-10-28,Kuala Terengganu,Terengganu,MAS,Malaysia,166.0,69.0,NaN
134593,137673,Jeffrey Webb,1998-10-27,Kuala Lumpur,Kuala Lumpur,MAS,Malaysia,173.0,65.0,NaN
134594,137674,Julian Yee,1997-05-26,Kuala Lumpur,Kuala Lumpur,MAS,Malaysia,166.0,60.0,NaN
135271,138434,P. Alagendra,1929-07-23,Kajang,Selangor,MAS,Malaya,NaN,NaN,NaN

In [45]:
# Satukan kedua tabel tersebut secara vertikal menjadi satu DataFrame baru bernama df_asean.

df_asean = pd.concat([INA,MAS])

In [46]:
df_asean

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
232,233,Yayuk Basuki,1970-11-30,Yogyakarta,Daerah Istimewa Yogyakarta,INA,Indonesia,165.0,55.0,NaN
233,234,Rossy Pratiwi Dipoyanti,1972-06-28,Bandung,Jawa Barat,INA,Indonesia,NaN,NaN,NaN
234,235,Finarsih,1972-02-08,Sleman,Jawa Tengah,INA,Indonesia,NaN,NaN,NaN
235,236,Ling Ling Agustin,1969-08-23,Kediri,Jawa Timur,INA,Indonesia,NaN,NaN,NaN
238,239,Zelin Resiana,1972-07-09,Magelang,Jawa Tengah,INA,Indonesia,169.0,58.0,NaN
...,...,...,...,...,...,...,...,...,...,...
132242,135093,Welson Sim,1997-03-29,Kuching,Sarawak,MAS,Malaysia,181.0,70.0,NaN
132243,135094,Mohammad Hafifi bin Mansor,1990-10-28,Kuala Terengganu,Terengganu,MAS,Malaysia,166.0,69.0,NaN
134593,137673,Jeffrey Webb,1998-10-27,Kuala Lumpur,Kuala Lumpur,MAS,Malaysia,173.0,65.0,NaN
134594,137674,Julian Yee,1997-05-26,Kuala Lumpur,Kuala Lumpur,MAS,Malaysia,166.0,60.0,NaN
135271,138434,P. Alagendra,1929-07-23,Kajang,Selangor,MAS,Malaya,NaN,NaN,NaN